packages/_example/scripts/db-seed.ts

refactor(seed): display error in console log

---

packages/agent/src/builder/agent.ts

fix: unpublished fields should be usable on actions

---

docs/datasources/custom/query-translation/read-only.md
packages/_example/src/datasources/sequelize/mssql.ts
packages/agent/src/agent/routes/access/chart.ts
packages/agent/test/agent/routes/access/chart.test.ts
packages/agent/test/agent/routes/modification/associate-related.test.ts
packages/agent/test/agent/routes/modification/delete-related.test.ts
packages/agent/test/agent/routes/modification/dissociate-delete-related.test.ts
packages/agent/test/agent/routes/modification/dissociate-related.test.ts
packages/datasource-dummy/src/collections/base.ts
packages/datasource-dummy/src/index.ts
packages/datasource-toolkit/src/decorators/computed/collection.ts
packages/datasource-toolkit/src/decorators/relation/collection.ts
packages/datasource-toolkit/src/interfaces/query/aggregation.ts
packages/datasource-toolkit/src/interfaces/query/filter/factory.ts
packages/datasource-toolkit/src/interfaces/query/filter/unpaginated.ts
packages/datasource-toolkit/src/interfaces/schema.ts
packages/datasource-toolkit/src/utils/collection.ts
packages/datasource-toolkit/test/__factories__/schema/many-to-many-schema.ts
packages/datasource-toolkit/test/interfaces/aggregation.test.ts
packages/datasource-toolkit/test/interfaces/filter-factory.test.ts
packages/datasource-toolkit/test/utils/collection.test.ts

fix: leaderboard chart and aggregation emulation

---

README.md
docs/datasources/custom/query-translation/read-only.md
packages/agent/src/agent/forestadmin-http-driver.ts
packages/datasource-toolkit/src/decorators/actions/context/base.ts

docs(wording): suggest the conventional case for Node.js

---

yarn.lock

fix(security): patch ansi-regex dependency vulnerabilities

---

yarn.lock

fix(security): patch moment dependency vulnerabilities

---

packages/datasource-sequelize/src/collection.ts
packages/datasource-sequelize/test/collection.test.ts

fix(datasource sequelize): add include from sort relation for list

---

packages/_example/scripts/db-seed-direct-sql.ts
packages/_example/scripts/db-seed.ts

chore(example): enhance database seed for datasource sql

---

docs/datasources/provided/databases/sql.md

docs(sql datasource): add sql datasource documentation

---

packages/agent/src/agent/utils/forest-schema/generator-collection.ts
packages/agent/test/agent/utils/forest-schema/generator-collection.test.ts

chore(agent): sort collection actions, fields and segments schema to avoid useless synchro

---

packages/datasource-sql/src/datasource.ts
packages/datasource-sql/test/datasource.test.ts

fix(datasource sql): has one detection

---

packages/agent/package.json
packages/agent/src/agent/forestadmin-http-driver.ts
yarn.lock

fix(cors): handle future private network access header

---

docs/datasources/README.md
docs/datasources/provided/databases/sql.md
docs/datasources/provided/orm/sequelize.md
packages/_example/src/agent.ts
packages/agent/src/index.ts
packages/agent/test/index.test.ts
packages/datasource-dummy/src/index.ts
packages/datasource-dummy/test/index.test.ts
packages/datasource-live/src/index.ts
packages/datasource-live/test/index.test.ts
packages/datasource-sequelize/src/index.ts
packages/datasource-sql/src/index.ts
packages/datasource-sql/test/index.test.ts

fix: import packages from js

---

packages/agent/src/agent/utils/http-driver-options.ts
packages/agent/test/agent/utils/http-driver-options.test.ts

fix(agent): force default value for some options when null or undefined are given

---

.releaserc.js

chore(release): change commit message to be more explicit

---

packages/_example/src/datasources/sequelize/postgres.ts
packages/datasource-sequelize/src/collection.ts
packages/datasource-sequelize/src/utils/query-converter.ts
packages/datasource-sequelize/test/collection.test.ts
packages/datasource-sequelize/test/utils/query-converter.unit.test.ts

fix(datasource sequelize):  build a correct where clause when there is relation on delete and update

---

packages/agent/src/agent/utils/forest-schema/generator-fields.ts
packages/agent/test/agent/utils/forest-schema/generator-fields_many-to-many.test.ts
packages/agent/test/agent/utils/forest-schema/generator-fields_one-to-many.test.ts
packages/agent/test/agent/utils/forest-schema/generator-fields_one-to-one.test.ts

fix: schema generation retrieves keys in the wrong collection

---

packages/_example/src/agent.ts
packages/agent/src/builder/agent.ts
packages/agent/src/builder/collection.ts
packages/agent/src/builder/decorators-stack.ts
packages/agent/test/builder/agent.test.ts
packages/agent/test/builder/collection.test.ts

refactor: make all decorator attributes private 

---

packages/_example/scripts/db-seed.ts

fix(example): the imports in the seed to prepare the dbs

---

packages/datasource-toolkit/src/decorators/computed/helpers/compute-fields.ts
packages/datasource-toolkit/src/decorators/computed/utils/flattener.ts
packages/datasource-toolkit/test/decorators/computed/utils.test.ts

fix: record flattener used for computed is corrupting records

---

packages/datasource-sql/package.json

build(datasource-sql): remove unused dependency

---

packages/agent/src/agent/routes/modification/update-relation.ts
packages/agent/test/agent/routes/modification/update-relation.test.ts

fix: can't set a relation to null in the detail-view form

---

packages/datasource-toolkit/src/decorators/computed/utils/deduplication.ts
packages/datasource-toolkit/test/decorators/computed/utils.test.ts

fix: fetching computed fields from a null relation calls the customer handler with nulls

---

docs/agent-customization/actions/README.md
docs/agent-customization/actions/forms.md
docs/agent-customization/actions/responses.md

docs: propagate naming change (registerAction -> addAction)

---

packages/datasource-toolkit/src/decorators/relation/collection.ts
packages/datasource-toolkit/test/decorators/relation/collection.test.ts

fix: invalid queries are made to resolve jointures

---

packages/_example/src/datasources/live/schema.ts
packages/datasource-live/src/datasource.ts
packages/datasource-live/src/index.ts
packages/datasource-live/src/types.ts
packages/datasource-live/src/utils/collection-schema-to-model-attributes-converter.ts
packages/datasource-live/src/utils/collection-schema-to-model-relations-converter.ts
packages/datasource-live/test/collection.test.ts
packages/datasource-live/test/datasource.test.ts
packages/datasource-live/test/utils/collection-schema-to-model-attributes-converter.unit.test.ts
packages/datasource-live/test/utils/collection-schema-to-model-relations-converter.unit.test.ts
packages/datasource-toolkit/src/interfaces/schema.ts

This is a pre-req for API charts

refactor(live): remove DatasourceSchema

---

packages/_example/connected-datasources.puml
packages/_example/datasources.puml
packages/_example/package.json
packages/_example/scripts/db-seed.ts
packages/_example/src/agent.ts
packages/_example/src/customizations/comment.ts
packages/_example/src/customizations/owner.ts
packages/_example/src/customizations/post.ts
packages/_example/src/datasources/typicode.ts
packages/_example/src/index.ts

This PR adds a custom connector in the examples.
While writing it, I uncovered a bug fixed here which should be merged first: https://github.com/ForestAdmin/agent-nodejs/pull/264

feat(example): add custom connector

---

packages/agent/src/builder/agent.ts
packages/agent/src/builder/collection.ts

refactor(builder): remove types from tsdoc

---

packages/agent/src/builder/decorators-stack.ts

refactor(builder): make decorator-stack class shorter

---

packages/agent/src/agent/routes/access/chart.ts
packages/agent/src/agent/routes/access/count-related.ts
packages/agent/src/agent/routes/access/count.ts
packages/agent/src/agent/routes/access/csv-related.ts
packages/agent/src/agent/routes/access/csv.ts
packages/agent/src/agent/routes/access/get.ts
packages/agent/src/agent/routes/access/list-related.ts
packages/agent/src/agent/routes/access/list.ts
packages/agent/src/agent/routes/modification/action.ts
packages/agent/src/agent/routes/modification/associate-related.ts
packages/agent/src/agent/routes/modification/create.ts
packages/agent/src/agent/routes/modification/delete.ts
packages/agent/src/agent/routes/modification/dissociate-delete-related.ts
packages/agent/src/agent/routes/modification/update-relation.ts
packages/agent/src/agent/routes/modification/update.ts
packages/agent/src/agent/utils/query-string.ts
packages/agent/test/agent/utils/query-string.test.ts

refactor(frontend): rename parseRecipient to parseCaller

---

packages/datasource-toolkit/src/context/collection-context.ts
packages/datasource-toolkit/src/context/relaxed-wrappers/collection.ts
packages/datasource-toolkit/src/context/relaxed-wrappers/datasource.ts
packages/datasource-toolkit/src/decorators/actions/collection.ts
packages/datasource-toolkit/src/decorators/actions/context/base.ts
packages/datasource-toolkit/src/decorators/actions/context/single.ts
packages/datasource-toolkit/test/context/wrapper.test.ts
packages/datasource-toolkit/test/decorators/actions/context.test.ts

refactor(context): simplify customization context

---

docs/agent-customization/relationships.md
docs/datasources/custom/README.md
packages/_example/connected-datasources.puml
packages/_example/datasources.puml
packages/_example/src/agent.ts
packages/agent/src/builder/agent.ts
packages/agent/test/builder/agent.test.ts
packages/datasource-sequelize/test/datasource.unit.test.ts
packages/datasource-sql/test/datasource.test.ts
packages/datasource-toolkit/src/decorators/datasource-decorator.ts
packages/datasource-toolkit/src/index.ts
packages/datasource-toolkit/test/base-datasource.test.ts
packages/datasource-toolkit/test/context/wrapper.test.ts
packages/datasource-toolkit/test/decorators/write/collection.test.ts

refactor: datasource naming consistency

---

packages/datasource-toolkit/src/decorators/operators-emulate/types.ts
packages/datasource-toolkit/test/decorators/operators-emulate/collection.test.ts

fix(autocomplete): improve operator replacement autocompletion

---

packages/_example/src/customizations/dvd.ts

refactor(example): fix typo in local variable name

---

packages/agent/test/builder/collection.test.ts
packages/datasource-toolkit/src/decorators/computed/collection.ts
packages/datasource-toolkit/test/decorators/computed/collection.test.ts

fix(computed): crash at construction when making computed fields which have zero dependencies

---

docs/datasources/README.md
docs/datasources/custom/README.md
docs/datasources/provided/databases/sql.md
docs/datasources/provided/orm/sequelize.md
packages/_example/src/agent.ts
packages/agent/src/index.ts
packages/agent/test/index.test.ts

fix(agent): export a factory to create the agent

---

packages/agent/src/agent/utils/forest-schema/generator-fields.ts
packages/agent/src/agent/utils/forest-schema/types.ts
packages/agent/test/agent/utils/forest-schema/generator-fields_column.test.ts

fix(schema): broken generation for composite types

---

packages/agent/src/agent/forestadmin-http-driver.ts
packages/agent/src/agent/utils/forest-http-api.ts
packages/agent/test/agent/forestadmin-http-driver.test.ts
packages/agent/test/agent/utils/forest-http-api.test.ts

fix(onboarding): display better errors when the agent fails to start

---

packages/_example/src/customizations/address.ts
packages/_example/src/customizations/comment.ts
packages/_example/src/customizations/customer.ts
packages/_example/src/customizations/dvd.ts
packages/_example/src/customizations/owner.ts
packages/_example/src/customizations/post.ts
packages/_example/src/customizations/rental.ts
packages/_example/src/customizations/store.ts
packages/agent/src/builder/collection.ts
packages/agent/test/builder/collection.test.ts

feat(builder): create one method per relation type in the collection customizer

---

packages/_example/docker-compose.yml
packages/_example/src/connections/mongoose.ts

chore(datasource mongoose): change connection port

---

packages/agent/src/agent/routes/access/csv.ts
packages/agent/test/agent/routes/access/csv.test.ts

fix(permissions): switch read to browse for csv permissions

---

docs/agent-customization/relationships.md
docs/datasources/custom/query-translation/relationships.md
docs/datasources/custom/structure.md

docs(relations): fix relation documentation

---

packages/_example/package.json
packages/_example/src/forest/agent.ts
packages/_example/src/forest/customizations/post.ts

chore(example): re add mongoose datasource inside example

---

packages/datasource-toolkit/src/decorators/publication/collection.ts
packages/datasource-toolkit/test/decorators/publication/collection.test.ts

fix: publication decorator should not return unpublished columns

---

packages/datasource-sequelize/src/collection.ts
packages/datasource-sequelize/src/utils/query-converter.ts
packages/datasource-sequelize/test/collection.test.ts
packages/datasource-sequelize/test/utils/query-converter.unit.test.ts

chore(datasource sequelize): refactor QueryConverter

---

packages/agent/src/builder/collection.ts
packages/datasource-toolkit/src/context/relaxed-wrappers/collection.ts
packages/datasource-toolkit/src/context/relaxed-wrappers/datasource.ts
packages/datasource-toolkit/src/decorators/actions/context/base.ts
packages/datasource-toolkit/src/decorators/actions/result-builder.ts

This handle a list of functions I used on a demo that are currently not documented in the API Ref, as well as a few issues I encounter while testing the examples

docs(api-reference): add more api reference for actions/collections & builder

---

packages/datasource-toolkit/src/decorators/computed/types.ts

fix(decorators): remove useless isRequired field

---

packages/_example/src/forest/typings.ts
packages/agent/src/builder/utils/typing-generator.ts
packages/agent/test/builder/utils/typing-generator.test.ts

fix(typing-generator): add simple quote around the collection and field name to support unconventional characters     

---

docs/agent-customization/fields/computed.md
docs/agent-customization/fields/write.md

docs(replaceFieldWriting): improve the documentation for the replaceFieldWriting

---

packages/agent/src/builder/collection.ts
packages/agent/src/builder/decorators-stack.ts
packages/agent/test/builder/collection.test.ts
packages/datasource-toolkit/src/decorators/rename-field/collection.ts
packages/datasource-toolkit/src/index.ts
packages/datasource-toolkit/test/decorators/rename-field/collection.test.ts

refactor(decorator): rename field decorator to be consistent with the rename collection decorator

---

packages/agent/src/agent/routes/system/error-handling.ts
packages/agent/src/agent/types.ts
packages/agent/test/agent/routes/system/error-handling.test.ts
packages/datasource-toolkit/src/decorators/write/collection.ts
packages/datasource-toolkit/src/errors.ts
packages/datasource-toolkit/src/index.ts
packages/datasource-toolkit/src/validation/condition-tree.ts
packages/datasource-toolkit/src/validation/field.ts
packages/datasource-toolkit/src/validation/record.ts
packages/datasource-toolkit/src/validation/sort.ts
packages/datasource-toolkit/test/decorators/write/collection.test.ts

chore(errors): add forbidden and unprocessable error

---

packages/agent/src/builder/decorators-stack.ts

fix(agent): move chart decorator to allow use sort emulate inside handler

---

packages/datasource-sql/src/datasource.ts
packages/datasource-sql/src/utils/default-value-parser.ts
packages/datasource-sql/test/datasource.test.ts
patches/sequelize+6.18.0.patch

fix(patch-package): remove feature change on sequelize handleShowTablesQuery

---

docs/datasources/provided/mongoose.md

docs: fix mongoose example documentation to javascript

---

packages/datasource-sequelize/src/collection.ts
packages/datasource-sequelize/src/utils/aggregation.ts
packages/datasource-sequelize/src/utils/query-converter.ts
packages/datasource-sequelize/src/utils/un-ambigous.ts
packages/datasource-sequelize/test/utils/aggregation.test.ts
packages/datasource-sequelize/test/utils/un-ambigous.test.ts

fix(datasource sequelize): aggregation get correctly nested relation

---

README.md

chore: update readme.md to be the same as other agent repo

---

package.json
yarn.lock

- [-] Ensure that Types have been updated according to your changes (if needed)

chore(security): upgrade lerna to ^5.1.8

---

docs/under-the-hood/queries/filters.md

docs(condition-tree): document the condition tree on the relations

---

docs/SUMMARY.md
docs/agent-customization/examples/README.md
docs/agent-customization/examples/upload-file-to-s3.md

docs(s3): add an example to document how to upload a file to s3

---

packages/_example/package.json
packages/datasource-live/package.json
packages/datasource-sequelize/package.json
packages/datasource-sequelize/src/collection.ts
packages/datasource-sequelize/src/datasource.ts
packages/datasource-sequelize/src/index.ts
packages/datasource-sequelize/src/utils/aggregation.ts
packages/datasource-sequelize/src/utils/date-aggregation-converter.ts
packages/datasource-sequelize/src/utils/model-to-collection-schema-converter.ts
packages/datasource-sequelize/src/utils/query-converter.ts
packages/datasource-sequelize/src/utils/type-converter.ts
packages/datasource-sequelize/test/utils/date-aggregation-converter.test.ts
packages/datasource-sql/package.json
packages/datasource-sql/src/utils/default-value-parser.ts
patches/sequelize+6.21.3.patch
yarn.lock

fix: update code and sequelize version to avoid crash

---

docs/agent-customization/fields/computed.md
packages/_example/src/forest/customizations/store.ts
packages/agent/src/builder/collection.ts
packages/agent/test/builder/collection.test.ts

feat(importField): make it writable by default

---

.github/workflows/build.yml

fix(api-reference): publish api reference even on the beta branch

---

docs/SUMMARY.md
docs/how-tos/running-forest-admin-on-multiple-instances.md
packages/agent/src/builder/utils/options-validator.ts

docs: how to run forest admin on multiple instances

---

packages/agent/src/agent/utils/forest-schema/generator-actions.ts

fix(actions): fix path generation for actions on windows

---

packages/datasource-sequelize/src/collection.ts
packages/datasource-sequelize/src/utils/error-handler.ts
packages/datasource-sequelize/test/utils/error-handler.test.ts

feat(sequelize): improve constraints error handling

---

packages/agent/src/builder/agent.ts
packages/agent/test/builder/agent.test.ts
packages/datasource-toolkit/src/composite-datasource.ts
packages/datasource-toolkit/src/decorators/chart/datasource.ts
packages/datasource-toolkit/src/decorators/datasource-decorator.ts
packages/datasource-toolkit/src/decorators/rename-collection/datasource.ts
packages/datasource-toolkit/src/index.ts
packages/datasource-toolkit/test/__factories__/datasource.ts
packages/datasource-toolkit/test/base-datasource.test.ts
packages/datasource-toolkit/test/composite-datasource.test.ts
packages/datasource-toolkit/test/decorators/chart/datasource.test.ts
packages/datasource-toolkit/test/decorators/rename-collection/datasource.test.ts

fix(builder): data-source charts are lost when mounted on the agent builder

---

packages/datasource-mongoose/src/index.ts

fix(mongoose): options are not required when creating the connector

---

packages/datasource-sql/src/datasource-factory.ts
packages/datasource-sql/test/datasource-factory.integration.test.ts
packages/datasource-sql/test/datasource-factory.unit.test.ts

fix(datasource-sql): skip models which do not have primary keys

---

packages/datasource-toolkit/src/decorators/relation/collection.ts
packages/datasource-toolkit/test/decorators/relation/collection.test.ts

fix(relation): use correct column when emulating filter on emulated many to one

---

packages/datasource-sequelize/src/utils/model-to-collection-schema-converter.ts
packages/datasource-sequelize/test/utils/model-to-collection-schema-converter.test.ts

fix: inverted keys in sequelize belongs to many

---

packages/datasource-toolkit/src/validation/field.ts
packages/datasource-toolkit/test/validation/condition-tree.test.ts
packages/datasource-toolkit/test/validation/field.test.ts

fix(validator): allow null value for the field value and use strict value for the ids. 

---

packages/agent/src/builder/agent.ts
packages/agent/src/builder/utils/typing-generator.ts
packages/agent/test/builder/agent.test.ts

fix: restart loop when using NestJS file watcher

---

packages/agent/src/agent/services/permissions.ts
packages/agent/src/agent/utils/forest-http-api.ts
packages/agent/test/agent/routes/access/chart.test.ts
packages/agent/test/agent/services/permissions.test.ts
packages/agent/test/agent/utils/forest-http-api.test.ts

fix: allow dev admin editors to see the chart they just created

---

packages/datasource-sql/src/introspection/introspector.ts

perf(datasource-sql): query structure, indexes and references in parallel

---

.husky/pre-push

chore: remove test execution on push

---

.releaserc.js

chore: add github and slack release action

---

.github/workflows/build.yml

ci: fix slack release step

---

.github/PULL_REQUEST_TEMPLATE.md

- [👹] Ensure that Types have been updated according to your changes (if needed)

chore: remove typing checkbox from pull-request template

---

.releaserc.js

ci: add packageName to slack step

---

.github/workflows/build.yml
package.json
typedoc.json
yarn.lock

chore: publish API reference

---

typedoc.json

docs: change api reference title

---

packages/agent/src/agent/routes/access/chart.ts

refactor(charts): make explicit calls to chart creation methods

---

packages/datasource-toolkit/src/validation/field.ts
packages/datasource-toolkit/test/validation/condition-tree.test.ts

fix: required enum now are validated correctly

---

packages/datasource-toolkit/src/decorators/actions/collection.ts
packages/datasource-toolkit/src/decorators/actions/types/actions.ts
packages/datasource-toolkit/src/decorators/operators-emulate/collection.ts
packages/datasource-toolkit/src/decorators/operators-emulate/types.ts
packages/datasource-toolkit/src/decorators/relation/collection.ts
packages/datasource-toolkit/src/decorators/relation/types.ts
packages/datasource-toolkit/src/decorators/search/collection.ts
packages/datasource-toolkit/src/decorators/search/types.ts
packages/datasource-toolkit/src/index.ts

refactor(datasource-toolkit): remove type aliases

---

docs/getting-started/install/autocompletion-and-typings.md
packages/_example/src/forest/customizations/account.ts
packages/_example/src/forest/customizations/comment.ts
packages/_example/src/forest/customizations/customer.ts
packages/_example/src/forest/customizations/dvd.ts
packages/_example/src/forest/customizations/owner.ts
packages/_example/src/forest/customizations/post.ts
packages/_example/src/forest/customizations/rental.ts
packages/_example/src/forest/customizations/store.ts
packages/agent/src/builder/agent.ts
packages/agent/src/builder/collection.ts
packages/agent/src/index.ts
packages/agent/test/index.test.ts

refactor: rename Collection to CollectionCustomizer

---

.github/workflows/build.yml

ci: fix unwanted cancel ci

---

packages/agent/src/builder/agent.ts
packages/agent/src/builder/framework-mounter.ts
packages/agent/test/builder/framework-mounter.test.ts

refactor(agent): move framework compatibility to separate class

---

packages/agent/src/agent/services/permissions.ts
packages/agent/src/agent/utils/forest-http-api.ts
packages/agent/test/agent/services/permissions.test.ts
packages/agent/test/agent/utils/forest-http-api.test.ts

fix(scope): properly translate scope condition

---

packages/agent/src/builder/collection.ts
packages/datasource-mongoose/src/collection.ts
packages/datasource-toolkit/src/context/relaxed-wrappers/collection.ts
packages/datasource-toolkit/src/decorators/actions/context/base.ts
packages/datasource-toolkit/src/decorators/hook/context/aggregate.ts
packages/datasource-toolkit/src/decorators/hook/context/delete.ts
packages/datasource-toolkit/src/decorators/hook/context/list.ts
packages/datasource-toolkit/src/decorators/hook/context/update.ts
packages/datasource-toolkit/src/decorators/operators-emulate/types.ts
packages/datasource-toolkit/src/decorators/search/types.ts
packages/datasource-toolkit/src/decorators/segment/types.ts
packages/datasource-toolkit/src/interfaces/query/aggregation.ts
packages/datasource-toolkit/src/interfaces/query/condition-tree/nodes/base.ts
packages/datasource-toolkit/src/interfaces/query/condition-tree/nodes/branch.ts
packages/datasource-toolkit/src/interfaces/query/condition-tree/nodes/leaf.ts
packages/datasource-toolkit/src/interfaces/query/filter/paginated.ts
packages/datasource-toolkit/src/interfaces/query/filter/unpaginated.ts
packages/datasource-toolkit/src/interfaces/query/sort/index.ts
packages/datasource-toolkit/src/interfaces/templates.ts

refactor(datasource-toolkit): use templates only for customization

---

packages/agent/src/builder/collection.ts
packages/agent/test/builder/collection.test.ts
packages/datasource-toolkit/src/index.ts

refactor(operator-emulation): use toolkit list of operators instead of frontend

---

docs/getting-started/quick-start.md

docs(quick-start): fix typos in quick start

---

packages/datasource-customizer/LICENSE
packages/datasource-customizer/jest.config.ts
packages/datasource-customizer/package.json
packages/datasource-customizer/src/index.ts
packages/datasource-customizer/test/index.test.ts
packages/datasource-customizer/tsconfig.eslint.json
packages/datasource-customizer/tsconfig.json

feat(datasource-customizer): add empty package

---

packages/datasource-sql/src/index.ts
packages/datasource-sql/src/introspection/helpers/default-value-parser.ts
packages/datasource-sql/src/introspection/helpers/sql-type-converter.ts
packages/datasource-sql/src/introspection/introspector.ts
packages/datasource-sql/src/introspection/types.ts
packages/datasource-sql/src/orm-builder/helpers/sequelize-type.ts
packages/datasource-sql/src/orm-builder/model.ts
packages/datasource-sql/test/datasource-factory.integration.test.ts
packages/datasource-sql/test/introspection/helpers/default-value-parser.test.ts
packages/datasource-sql/test/introspection/helpers/sql-type-converter.test.ts
packages/datasource-toolkit/test/validation/condition-tree.test.ts

feat(datasource-sql): allow skipping database introspection

---

packages/datasource-customizer/src/collection-customizer.ts
packages/datasource-customizer/src/decorators/actions/types/actions.ts
packages/datasource-customizer/src/decorators/hook/types.ts
packages/datasource-customizer/src/index.ts

docs: add missing export for api ref

---

docs/agent-customization/actions/forms.md
docs/under-the-hood/queries/README.md

docs: put the right link of API reference

---

docs/agent-customization/actions/README.md
docs/agent-customization/actions/forms.md
docs/agent-customization/actions/responses.md
docs/agent-customization/charts.md
docs/agent-customization/fields/computed.md
docs/agent-customization/fields/filter.md
docs/agent-customization/fields/import-rename-delete.md
docs/agent-customization/fields/sort.md
docs/agent-customization/fields/validation.md
docs/agent-customization/fields/write.md
docs/agent-customization/hooks/README.md
docs/agent-customization/relationships/README.md
docs/agent-customization/relationships/computed-fks.md
docs/agent-customization/relationships/multiple-records.md
docs/agent-customization/relationships/under-the-hood.md
docs/agent-customization/search.md
docs/agent-customization/segments.md

docs(agent customization): fix typos

---

docs/agent-customization/examples/upload-file-to-s3.md

docs(example): fix typos

---

docs/SUMMARY.md
docs/datasources/custom/query-translation/README.md
docs/under-the-hood/data-model/relationships.md
docs/under-the-hood/data-model/typing.md
docs/under-the-hood/queries/README.md
docs/under-the-hood/queries/aggregations.md
docs/under-the-hood/queries/fields-projections.md
docs/under-the-hood/queries/filters.md

docs(under the hood): fix typos

---

packages/agent/src/services/authorization/internal/rendering-permission.ts
packages/agent/src/services/authorization/internal/types.ts
packages/agent/test/services/authorization/internal/rendering-permission.test.ts

fix(charts): allow editors to retrieve any chart

---

package.json

chore(ci): display only failing doc links when validating

---

docs/datasources/custom/relationships.md

docs(relations): remove alternative relation example

---

packages/_example/package.json
packages/agent/package.json
yarn.lock

chore: fix nestjs express vulnerabilities

---

docs/agent-customization/fields/README.md
docs/agent-customization/relationships/computed-fks.md
docs/datasources/connection/relationships.md

docs: fix typos in documentation

---

packages/datasource-toolkit/src/factory.ts

fix: fix build version issue

---

packages/datasource-toolkit/src/base-datasource.ts

fix: improve the error message when a collection is not found

---

README.md

chore: fix docs link in readme.md

---

.github/workflows/build.yml

ci: fix CI workflow by disabling workspaces-update

---

docs/deployment/forest-cli-commands/README.md

chore: remove beta label from toolbelt install

---

docs/agent-customization/relationships/computed-fks.md
packages/datasource-customizer/src/collection-customizer.ts
packages/datasource-customizer/src/types.ts
packages/datasource-customizer/test/collection-customizer.test.ts

feat(customizer): automatically detect fields that are computed before relations

---

packages/datasource-customizer/src/decorators/decorators-stack.ts

fix(customizer): write overrides should be called before record validation

---

.github/workflows/build.yml

chore(force-release): use the github_token to authenticate the user instead of GH_TOKEN

---

.github/workflows/build.yml

chore: give right to write to the github action bot

---

docs/SUMMARY.md
docs/agent-customization/plugins/README.md
docs/agent-customization/plugins/custom.md
packages/agent/src/agent.ts
packages/agent/test/agent.test.ts
packages/datasource-customizer/src/collection-customizer.ts
packages/datasource-customizer/src/datasource-customizer.ts
packages/datasource-customizer/src/decorators/decorators-stack.ts
packages/datasource-customizer/src/plugins/add-external-relation.ts
packages/datasource-customizer/src/plugins/import-field.ts
packages/datasource-customizer/src/types.ts
packages/datasource-customizer/test/collection-customizer.test.ts
packages/datasource-customizer/test/datasource-customizer.test.ts

feat(customization): plugin system

---

packages/agent/src/routes/system/error-handling.ts
packages/agent/test/routes/system/error-handling.test.ts

feat: support custom errors with data and add more information about error

---

docs/datasources/provided/sql.md
packages/_example/src/forest/agent.ts
packages/_example/src/forest/customizations/card.ts
packages/datasource-sql/src/index.ts
packages/datasource-sql/src/types.ts

feat(datasource-sql): add advanced options on createSqlDataSource

---

packages/agent/src/routes/access/chart.ts
packages/agent/test/routes/access/chart.test.ts

…played correctly
linked to CU-35jy8mp

fix(line-chart): line chart with null value on group by should return some values  

---

docs/agent-customization/examples/upload-file-to-s3.md

chore(documentation): fix link to install AWS SDK

---

packages/agent/src/routes/access/chart.ts
packages/agent/src/utils/query-string.ts
packages/agent/test/routes/access/chart.test.ts
packages/agent/test/services/authorization/authorization.test.ts
packages/forestadmin-client/src/charts/types.ts
packages/forestadmin-client/src/index.ts
packages/forestadmin-client/src/permissions/hash-chart.ts
packages/forestadmin-client/src/permissions/permission-with-cache.ts
packages/forestadmin-client/src/permissions/rendering-permission.ts
packages/forestadmin-client/src/permissions/types.ts
packages/forestadmin-client/src/types.ts
packages/forestadmin-client/test/permissions/hash-chart.test.ts
packages/forestadmin-client/test/permissions/permission-with-cache.test.ts
packages/forestadmin-client/test/permissions/rendering-permission.test.ts

refactor(charts): update chart request to match forestadmin backend format #491

---

packages/_example/connected-datasources.puml
packages/_example/datasources.puml
packages/_example/scripts/db-seed.ts
packages/_example/src/connections/sequelize-postgres.ts
packages/_example/src/forest/agent.ts
packages/_example/src/forest/customizations/review.ts
packages/_example/src/forest/typings.ts
packages/agent/src/routes/modification/create.ts
packages/agent/test/routes/modification/create.test.ts

fix: allow to create a record when the client sends a null relation

---

packages/agent/package.json
patches/openid-client+5.2.1.patch
yarn.lock

fix(security): update openid-client to latest version

---

packages/agent/src/utils/forest-schema/generator-collection.ts
packages/agent/src/utils/forest-schema/generator-fields.ts
packages/agent/test/utils/forest-schema/generator-collection.test.ts
packages/agent/test/utils/forest-schema/generator-fields_many-to-many.test.ts
packages/datasource-customizer/src/decorators/publication-field/collection.ts
packages/datasource-toolkit/src/utils/schema.ts
packages/datasource-toolkit/test/utils/schema.test.ts

fix(schema-emitter): better handling of schema edge-cases

---

packages/agent/src/routes/access/chart.ts
packages/agent/src/services/authorization/authorization.ts
packages/agent/test/__factories__/authorization/authorization.ts
packages/agent/test/__factories__/forest-admin-client.ts
packages/agent/test/routes/access/chart.test.ts
packages/agent/test/services/authorization/authorization.test.ts
packages/forestadmin-client/package.json
packages/forestadmin-client/src/index.ts
packages/forestadmin-client/src/permissions/errors/chained-sql-query-error.ts
packages/forestadmin-client/src/permissions/errors/empty-sql-query-error.ts
packages/forestadmin-client/src/permissions/errors/non-select-sql-query-error.ts
packages/forestadmin-client/src/permissions/permission-with-cache.ts
packages/forestadmin-client/src/permissions/rendering-permission.ts
packages/forestadmin-client/src/permissions/verify-sql-query.ts
packages/forestadmin-client/src/types.ts
packages/forestadmin-client/test/__factories__/permissions/permission.ts
packages/forestadmin-client/test/__factories__/permissions/rendering-permission.ts
packages/forestadmin-client/test/permissions/permission-with-cache.test.ts
packages/forestadmin-client/test/permissions/rendering-permission.test.ts

fix(chart/segment): check that query is valid before executing it

---

packages/datasource-mongoose/src/collection.ts
packages/datasource-mongoose/src/utils/helpers.ts
packages/datasource-mongoose/test/_helpers.ts
packages/datasource-mongoose/test/collection/collection_update.test.ts

fix(mongoose): when updating a field on flattened collections, all fields are overwritten

---

packages/_example/scripts/db-seed.ts
packages/agent/src/utils/csv-generator.ts
packages/agent/test/routes/access/csv-related.test.ts
packages/agent/test/routes/access/csv.test.ts
packages/agent/test/utils/csv-generator.test.ts

fix(export-csv): remove the limit/skip arguments and adding a row delimiter after each chunk 

---

.github/workflows/build.yml

ci(documentation): publish only api reference from main branch

---

packages/agent/src/utils/options-validator.ts
packages/agent/test/utils/http-driver-options.test.ts

fix(options): set minimum permissions cache duration

---

packages/datasource-customizer/src/typing-generator.ts
packages/datasource-customizer/test/typing-generator.test.ts
packages/datasource-sequelize/src/utils/model-to-collection-schema-converter.ts
packages/datasource-sequelize/test/utils/model-to-collection-schema-converter.test.ts

fix(sequelize): fields of type "enum list" are missing "enumValues"

---

packages/agent/src/routes/modification/delete.ts
packages/agent/test/routes/modification/delete.test.ts

fix(security): add missing permission check on list-delete

---

packages/plugin-import-fields/package.json

fix: build broken because of missing properties in package.json

---

packages/agent/src/routes/modification/delete.ts
packages/agent/test/routes/modification/delete.test.ts
packages/plugin-import-fields/package.json

chore: merge e86edbea0a8a6ccb1e48e43c0259fc044e85b02e

---

packages/_example/CHANGELOG.md
packages/agent/CHANGELOG.md
packages/datasource-customizer/CHANGELOG.md
packages/datasource-dummy/CHANGELOG.md
packages/datasource-sequelize/CHANGELOG.md
packages/datasource-sql/CHANGELOG.md
packages/plugin-import-fields/CHANGELOG.md

chore: merge main

---

packages/agent/test/__factories__/forest-admin-client.ts
packages/agent/test/__factories__/forest-admin-http-driver-services.ts
packages/forestadmin-client/src/charts/chart-handler.ts
packages/forestadmin-client/src/permissions/rendering-permission.ts
packages/forestadmin-client/src/permissions/verify-sql-query.ts
packages/forestadmin-client/src/types.ts
packages/forestadmin-client/src/utils/context-variables-injector.ts
packages/forestadmin-client/test/__factories__/chart/chart-handler.ts
packages/forestadmin-client/test/chart/chart-handler.test.ts
packages/forestadmin-client/test/permissions/rendering-permission.test.ts
packages/forestadmin-client/test/permissions/verify-sql-query.test.ts
packages/forestadmin-client/test/utils/context-variables-injector.test.ts

feat(chart): add support for context variables inside SQL query

---

docs/agent-customization/charts/value.md

docs: typo

---

packages/forestadmin-client/test/utils/chart-detector.test.ts

test: add tests on ChartDetector

---

packages/forestadmin-client/package.json
packages/forestadmin-client/src/charts/types.ts
packages/forestadmin-client/src/forest-admin-client-with-cache.ts
packages/forestadmin-client/src/permissions/rendering-permission.ts
packages/forestadmin-client/src/permissions/types.ts
packages/forestadmin-client/src/types.ts
packages/forestadmin-client/src/utils/context-variables-injector.ts
packages/forestadmin-client/test/chart/chart-handler.test.ts
packages/forestadmin-client/test/permissions/hash-chart.test.ts
packages/forestadmin-client/test/permissions/rendering-permission.test.ts
packages/forestadmin-client/test/utils/context-variables-injector.test.ts

refactor(forestadmin-client): infer raw tree type from plain condition tree

---

packages/forestadmin-client/test/__factories__/permissions/rendering-permission.ts
packages/forestadmin-client/test/permissions/rendering-permission.test.ts
packages/forestadmin-client/test/utils/context-variables-instantiator.test.ts

test: add test for getTeam, getUser and context injector instantiator file

---

jest.config.ts
packages/forestadmin-client/src/index.ts
packages/forestadmin-client/src/utils/default-logger.ts
packages/forestadmin-client/test/index.test.ts
packages/forestadmin-client/test/utils/default-logger.test.ts

test: add tests to the forestadmin client factory

---

packages/forestadmin-client/src/permissions/forest-http-api.ts

refactor: remove a useless error handler

---

packages/forestadmin-client/src/permissions/generate-actions-from-permissions.ts

refactor: remove a useless condition

---

packages/forestadmin-client/test/permissions/is-segment-query-authorized.test.ts

test: add a test when the authorized segments are falsy

---

packages/forestadmin-client/test/permissions/verify-approval.test.ts

test: add tests on verify-approvals

---

packages/agent/test/services/authorization/authorization.test.ts

test: add a unit test on the authorization service

---

packages/agent/src/routes/modification/action.ts
packages/agent/test/routes/modification/action.test.ts

fix(actions): global actions should ignore record selection

---

packages/agent/src/routes/security/ip-whitelist.ts
packages/agent/src/utils/forest-http-api.ts
packages/agent/test/__factories__/forest-admin-client.ts
packages/agent/test/routes/security/ip-whitelist.test.ts
packages/agent/test/utils/forest-http-api.test.ts
packages/forestadmin-client/src/forest-admin-client-with-cache.ts
packages/forestadmin-client/src/index.ts
packages/forestadmin-client/src/ip-whitelist/index.ts
packages/forestadmin-client/src/ip-whitelist/loader.ts
packages/forestadmin-client/src/ip-whitelist/types.ts
packages/forestadmin-client/src/types.ts
packages/forestadmin-client/test/__factories__/index.ts
packages/forestadmin-client/test/__factories__/ip-whitelist/index.ts
packages/forestadmin-client/test/forest-admin-client-with-cache.test.ts
packages/forestadmin-client/test/ip-whitelist/index.test.ts

refactor: move ip whitelist from agent to forestadmin-client

---

packages/datasource-mongoose/src/collection.ts
packages/datasource-mongoose/test/collection/collection_update.test.ts

fix(datasource mongoose): use updateOne when there are only one record to allow mongoose hook

---

packages/_example/src/forest/typings.ts
packages/datasource-mongoose/src/collection.ts
packages/datasource-mongoose/src/mongoose/schema.ts
packages/datasource-mongoose/src/utils/helpers.ts
packages/datasource-mongoose/src/utils/pipeline/reparent.ts
packages/datasource-mongoose/src/utils/pipeline/virtual-fields.ts
packages/datasource-mongoose/src/utils/schema/fields.ts
packages/datasource-mongoose/test/collection/collection_create.test.ts
packages/datasource-mongoose/test/collection/collection_delete.test.ts
packages/datasource-mongoose/test/collection/collection_update.test.ts
packages/datasource-mongoose/test/future.test.ts
packages/datasource-mongoose/test/utils/pipeline/reparent.test.ts
packages/datasource-mongoose/test/utils/pipeline/virtual-fields.test.ts

fix(datasource mongoose): replace _pid by parentId more understandable error

---

packages/forestadmin-client/src/index.ts

chore: export client types for full hosted

---

packages/forestadmin-client/src/index.ts

chore(force-release): force a release to export the types

---

packages/agent/src/routes/system/error-handling.ts
packages/agent/test/routes/system/error-handling.test.ts

fix(error-handling): prevent data leak during error handling

---

packages/forestadmin-client/src/permissions/action-permission.ts
packages/forestadmin-client/src/permissions/generate-actions-from-permissions.ts
packages/forestadmin-client/src/permissions/permission-with-cache.ts
packages/forestadmin-client/test/permissions/action-permission.test.ts
packages/forestadmin-client/test/permissions/generate-actions-from-permissions.test.ts
packages/forestadmin-client/test/permissions/permission-with-cache.test.ts

refactor(action-permissions): split concernes and simplify implementation

---

packages/datasource-customizer/src/decorators/decorators-stack.ts
packages/datasource-customizer/src/decorators/operators-emulate/collection.ts
packages/datasource-customizer/src/decorators/operators-equivalence/collection.ts
packages/datasource-customizer/test/decorators/operators-emulate/collection.test.ts
packages/datasource-customizer/test/decorators/operators-equivalence/collection.test.ts

fix(customizer): resolve operator equivalence between datasource composition and computed fields

---

packages/agent/src/index.ts
packages/forestadmin-client/src/index.ts
packages/forestadmin-client/src/schema/index.ts

chore(force-release): export classes for the agent-generator package

---

packages/datasource-mongoose/src/collection.ts
packages/datasource-mongoose/test/_helpers.ts
packages/datasource-mongoose/test/collection/collection_create.test.ts

feat(mongoose): convert mongoose validation errors so that they show up on the frontend

---

packages/plugin-flattener/package.json
packages/plugin-flattener/src/index.ts

fix(plugin-flattener): fix list of published files

---

packages/_example/package.json
packages/agent/package.json
packages/forestadmin-client/package.json
yarn.lock

chore(force-release): bump superagent to fix qs vulnerability

---

packages/_example/src/forest/customizations/account.ts
packages/forestadmin-client/src/utils/server.ts
packages/forestadmin-client/test/utils/server.test.ts

fix: display error message from the server when provided

---

packages/datasource-customizer/test/decorators/segment/collection.test.ts

test(customizer): fix segment decorator test

---

packages/datasource-customizer/src/decorators/computed/helpers/compute-fields.ts
packages/datasource-customizer/src/decorators/computed/utils/flattener.ts
packages/datasource-customizer/test/decorators/computed/utils.test.ts
packages/plugin-flattener/src/flatten-column/helpers.ts

fix(computed): keep track of nested null values when building DAG for computation

---

.github/workflows/build.yml
package.json

ci: improve workflow by updating action dependencies and reducing time to spin up docker containers

---

docs/datasources/connection/naming-conflicts.md
packages/datasource-customizer/src/datasource-customizer.ts
packages/datasource-customizer/src/decorators/rename-collection/datasource.ts
packages/datasource-customizer/src/types.ts
packages/datasource-customizer/test/datasource-customizer.test.ts
packages/datasource-customizer/test/decorators/rename-collection/datasource.test.ts

fix(customizer): add support for collection renaming function

---

packages/datasource-sequelize/src/utils/query-converter.ts
packages/datasource-sequelize/src/utils/type-converter.ts
packages/datasource-sequelize/test/utils/query-converter.unit.test.ts
packages/datasource-sequelize/test/utils/type-converter.unit.test.ts

fix(sequelize): invalid query generated when using the blank operator on uuid

---

docs/getting-started/install/expose/using-standalone.md
packages/agent/src/framework-mounter.ts

fix(agent): default to using the unspecified IPv6 and PORT environment variable

---

packages/agent/src/routes/system/error-handling.ts
packages/agent/test/routes/system/error-handling.test.ts
packages/datasource-toolkit/src/errors.ts
packages/datasource-toolkit/test/errors.test.ts

Linked to CU-35d7gta, CU-35d7h40, CU-35d7h1p

refactor: simplify error management by introducing a parent error class

---

.github/workflows/build.yml

chore: lint the built source code to avoid errors

---

packages/forestadmin-client/src/index.ts
packages/forestadmin-client/src/types.ts

Linked to CU-35d7h4d, CU-35d7h2b, CU-35d7gv6

fix: add missing type exports for external uses

---

packages/forestadmin-client/src/permissions/types.ts

Linked to CU-35d7h4d, CU-35d7h2b, CU-35d7gv6

fix: export defined types for permissions

---

packages/agent/src/utils/forest-schema/generator-fields.ts
packages/agent/test/utils/forest-schema/generator-fields_many-to-many.test.ts
packages/agent/test/utils/forest-schema/generator-fields_one-to-many.test.ts

fix(agent): mark all one-to-many and many-to-many relations as sortable

---

packages/forestadmin-client/src/permissions/action-permission.ts
packages/forestadmin-client/src/permissions/generate-actions-from-permissions.ts
packages/forestadmin-client/src/permissions/permission-with-cache.ts
packages/forestadmin-client/test/__factories__/permissions/action-permission.ts
packages/forestadmin-client/test/permissions/action-permission.test.ts
packages/forestadmin-client/test/permissions/generate-actions-from-permissions.test.ts
packages/forestadmin-client/test/permissions/permission-with-cache.test.ts

fix(requires-approval): development environment should trigger without requiring an approval

---

packages/agent/src/utils/query-string.ts

feat(agent): provide detail when projections fail to validate

---

packages/datasource-mongoose/src/utils/pipeline/filter.ts

refactor(mongoose): remove verbosity

---

packages/forestadmin-client/src/build-application-services.ts
packages/forestadmin-client/src/index.ts
packages/forestadmin-client/src/permissions/action-permission.ts
packages/forestadmin-client/src/permissions/forest-http-api.ts
packages/forestadmin-client/src/permissions/rendering-permission.ts
packages/forestadmin-client/src/permissions/user-permission.ts
packages/forestadmin-client/src/types.ts
packages/forestadmin-client/test/__factories__/forest-admin-server-interface.ts
packages/forestadmin-client/test/__factories__/index.ts
packages/forestadmin-client/test/__factories__/permissions/action-permission.ts
packages/forestadmin-client/test/__factories__/permissions/rendering-permission.ts
packages/forestadmin-client/test/__factories__/permissions/user-permission.ts
packages/forestadmin-client/test/permissions/action-permission.test.ts
packages/forestadmin-client/test/permissions/forest-http-api.test.ts
packages/forestadmin-client/test/permissions/rendering-permission.test.ts
packages/forestadmin-client/test/permissions/user-permission.test.ts

refactor(client): expose some methods to mock all the https calls

---

packages/datasource-customizer/src/collection-customizer.ts
packages/datasource-customizer/src/datasource-customizer.ts
packages/datasource-customizer/src/decorators/decorators-stack.ts
packages/datasource-customizer/src/decorators/validation/collection.ts
packages/datasource-customizer/test/collection-customizer.test.ts

fix(customizer): validation decorator should only validate its own rules

---

docs/agent-customization/relationships/single-record.md

docs(relationships): add hint to explain emulated relation sorting

---

packages/datasource-sequelize/src/collection.ts
packages/datasource-sequelize/src/utils/aggregation.ts
packages/datasource-sequelize/test/collection.test.ts

fix(datasource-sequelize): cast aggregation results when numbers are expected

---

packages/agent/src/agent.ts
packages/agent/src/types.ts
packages/agent/src/utils/options-validator.ts
packages/agent/test/__factories__/forest-admin-http-driver-options.ts
packages/agent/test/agent.test.ts
packages/agent/test/utils/http-driver-options.test.ts

feat(agent): allow skipping sending the schema

---

packages/datasource-sql/src/index.ts
packages/datasource-sql/src/types.ts
packages/datasource-sql/test/_helpers/setup-id-is-not-a-pk.ts
packages/datasource-sql/test/_helpers/setup-using-all-types.ts
packages/datasource-sql/test/_helpers/setup-using-relations.ts
packages/datasource-sql/test/datasource-factory.integration.test.ts

feat(datasource-sql): allow construction with both uri and options

---

packages/agent/src/routes/modification/action/action-authorization.ts
packages/agent/src/routes/modification/action/action.ts
packages/agent/test/routes/modification/action/action-authorization.test.ts
packages/agent/test/routes/modification/action/action.test.ts

fix(custom-actions): return async enum values of custom action forms instead of a ForbiddenError

---

packages/datasource-sql/src/index.ts
packages/datasource-sql/src/introspection/errors.ts
packages/datasource-sql/src/introspection/introspector.ts
packages/datasource-sql/test/datasource-factory.integration.test.ts
packages/datasource-sql/test/introspection/introspector.test.ts

refactor(introspection): catch all the errors to throw our errors

---

packages/datasource-sequelize/src/utils/type-converter.ts
packages/datasource-sql/src/introspection/helpers/sql-type-converter.ts
packages/datasource-sql/src/introspection/types.ts
packages/datasource-sql/src/orm-builder/helpers/sequelize-type.ts
packages/datasource-sql/src/orm-builder/model.ts
packages/datasource-sql/test/introspection/helpers/sql-type-converter.test.ts
packages/datasource-sql/test/orm-builder/model.test.ts

fix(datasource-sql): allow using custom enum names

---

packages/datasource-sequelize/src/utils/query-converter.ts
packages/datasource-sequelize/test/utils/query-converter.unit.test.ts

fix: not contains filter generate an error in sequelize

---

packages/datasource-sql/src/introspection/helpers/sql-type-converter.ts
packages/datasource-sql/src/introspection/types.ts
packages/datasource-sql/src/orm-builder/helpers/sequelize-type.ts
packages/datasource-sql/test/introspection/helpers/sql-type-converter.test.ts
packages/datasource-sql/test/orm-builder/model.test.ts

fix(datasource-sql): make enumlist typing case sensitive and schema aware

---

packages/agent/src/agent.ts
packages/agent/src/index.ts
packages/agent/src/utils/forest-schema/generator-collection.ts
packages/agent/src/utils/forest-schema/generator.ts
packages/agent/test/agent.test.ts
packages/agent/test/utils/forest-schema/generator.test.ts
packages/forestadmin-client/src/forest-admin-client-with-cache.ts
packages/forestadmin-client/src/schema/index.ts
packages/forestadmin-client/src/schema/types.ts
packages/forestadmin-client/src/types.ts
packages/forestadmin-client/test/forest-admin-client-with-cache.test.ts
packages/forestadmin-client/test/schema/index.test.ts

fix(schema): use forest-express schema format for CLI compatibility

---

packages/agent/src/utils/forest-schema/generator.ts
packages/agent/test/utils/forest-schema/generator.test.ts

fix(schema): must be sorted by collection name to avoid conflict

---

packages/datasource-customizer/test/decorators/publication-collection/datasource.test.ts

chore(decorator): fix PublicationCollectionDataSourceDecorator test

---

yarn.lock

fix(security): patch sequelize vulnerabilities

---

packages/datasource-sql/src/orm-builder/helpers/relation-extractor.ts
packages/datasource-sql/src/orm-builder/helpers/relation-name-generator.ts

refactor(datasource-sql): remove duplication

---

docs/SUMMARY.md
docs/agent-customization/plugins/provided/export-advanced.md
packages/plugin-export-advanced/LICENSE
packages/plugin-export-advanced/jest.config.ts
packages/plugin-export-advanced/package.json
packages/plugin-export-advanced/src/index.ts
packages/plugin-export-advanced/src/renderers/csv.ts
packages/plugin-export-advanced/src/renderers/index.ts
packages/plugin-export-advanced/src/renderers/json.ts
packages/plugin-export-advanced/src/renderers/xlsx.ts
packages/plugin-export-advanced/src/types.ts
packages/plugin-export-advanced/src/utils/get-field-value.ts
packages/plugin-export-advanced/test/index.test.ts
packages/plugin-export-advanced/tsconfig.eslint.json
packages/plugin-export-advanced/tsconfig.json
typedoc.json
yarn.lock

feat(advanced-export): add new plugin which allows better exports

---

packages/agent/src/routes/modification/update.ts
packages/agent/src/services/serializer.ts
packages/agent/test/routes/modification/update.test.ts
packages/agent/test/services/serializer.test.ts

fix(agent): allow updating records which have readonly ids

---

packages/datasource-mongoose/src/types.ts
packages/datasource-mongoose/src/utils/pipeline/filter.ts
packages/datasource-mongoose/src/utils/schema/fields.ts
packages/datasource-mongoose/src/utils/version-manager.ts
packages/datasource-mongoose/test/utils/schema/fields_flattener.test.ts
packages/datasource-mongoose/test/utils/version-manager.test.ts

fix(datasource-mongoose): mongoose 7.0 should return the right type for _id

---

packages/datasource-sql/src/index.ts
packages/datasource-sql/test/index.test.ts

fix(sql-datasource): use schema when it is given in the connection string

---

docs/agent-customization/relationships/computed-fks.md
packages/agent/test/routes/modification/delete-related.test.ts
packages/agent/test/routes/modification/dissociate-related.test.ts
packages/datasource-toolkit/src/interfaces/query/filter/factory.ts
packages/datasource-toolkit/test/interfaces/filter-factory.test.ts
packages/datasource-toolkit/test/utils/collection.test.ts

fix(computed-fks): using computed foreign keys requires implementing the Present operator

---

yarn.lock

fix(security): patch sqlite3 vulnerabilities

---

packages/datasource-customizer/src/decorators/computed/helpers/compute-fields.ts
packages/datasource-customizer/src/plugins/add-external-relation.ts
packages/datasource-customizer/test/collection-customizer.test.ts
packages/plugin-aws-s3/src/field/create-field.ts

feat(computed): remove need for promise.all on customer code when using async handler

---

docs/datasources/provided/sql.md

docs(sql-datasource): document the 'uri' option

---

.husky/pre-push

build(hooks): remove pre-push hook

---

packages/_example/package.json
packages/datasource-mongoose/package.json
packages/datasource-mongoose/src/collection.ts
yarn.lock

chore(mongoose-datasource): bump mongoose to 7.0 [force-release]

---

packages/datasource-sql/src/introspection/helpers/sql-type-converter.ts
packages/datasource-sql/test/introspection/helpers/sql-type-converter.test.ts

feat(datasource-sql): add support for MySQL BIT(1) type

---

docs/getting-started/migrating/steps/README.md

docs: fix broken link

---

packages/agent/src/framework-mounter.ts
packages/agent/test/framework-mounter.test.ts

fix: handle standalone server errors when agent is starting

---

docs/getting-started/migrating/README.md

docs(migration): do not mark rails/python/php as legacy before upgrading them

---

packages/agent/src/agent.ts
packages/agent/src/types.ts
packages/agent/src/utils/forest-schema/generator.ts
packages/agent/test/__data__/agent-schema.json
packages/agent/test/__factories__/forest-admin-http-driver-options.ts
packages/agent/test/agent.test.ts
packages/agent/test/utils/forest-schema/generator.test.ts
packages/forestadmin-client/src/schema/types.ts
packages/forestadmin-client/test/forest-admin-client-with-cache.test.ts
packages/forestadmin-client/test/schema/index.test.ts

refactor(webhook-custom-actions): allow to declare the activation of webhook custom actions

---

packages/datasource-sql/src/introspection/introspector.ts

fix(datasource-sql): remove dangling references to skipped entities in database introspection

---

packages/datasource-sequelize/src/utils/type-converter.ts
packages/datasource-sequelize/test/utils/type-converter.unit.test.ts

refactor(datasource-toolkit): remove dead code

---

packages/datasource-customizer/src/collection-customizer.ts

docs(datasource-customizer): add jsdoc to the addHook function

---

.github/workflows/build.yml

chore: correctly release alpha and beta versions

---

.github/workflows/build.yml

chore: only publish the API reference on main

---

packages/forestadmin-client/src/build-application-services.ts
packages/forestadmin-client/src/model-customizations/model-customization-from-api.ts
packages/forestadmin-client/src/permissions/forest-http-api.ts
packages/forestadmin-client/src/types.ts
packages/forestadmin-client/test/__factories__/forest-admin-server-interface.ts
packages/forestadmin-client/test/__factories__/model-customizations/model-customization-from-api.ts
packages/forestadmin-client/test/model-customizations/model-customization-from-api.test.ts
packages/forestadmin-client/test/permissions/forest-http-api.test.ts

Linked to CU-860qgzc55 and CU-860qgzc6w

refactor(webhook-custom-actions): allow customization retrieval to be mocked for FA cloud [force release]

---

packages/datasource-dummy/src/index.ts

Fix https://github.com/ForestAdmin/agent-nodejs/issues/627

fix(datasource-dummy): correct relation definition

---

packages/datasource-customizer/src/decorators/search/collection.ts

fix(customizer): crash at startup when using collections with native actions

---

packages/agent/src/utils/query-string.ts
packages/agent/test/utils/query-string.test.ts

fix(agent): improve error message when validating projections

---

LICENSE

chore: add GPL3 license in the root folder

---

packages/agent/src/agent.ts
packages/agent/src/services/model-customizations/execute-webhook.ts
packages/agent/test/agent.test.ts
packages/agent/test/services/model-customizations/execute-webhook.test.ts

fix(webhook-custom-actions): improve error reporting when calling a webhook

---

packages/datasource-sql/src/index.ts

fix(datasource-sql): export missing type

---

packages/agent/src/services/model-customizations/execute-webhook.ts
packages/agent/test/services/model-customizations/execute-webhook.test.ts
packages/forestadmin-client/src/model-customizations/types.ts
packages/forestadmin-client/test/model-customizations/model-customization-from-api.test.ts

refactor(webhook-custom-actions): change action configuration structure [force release]

---

packages/datasource-sequelize/package.json
packages/datasource-sql/docker-compose.yml
packages/datasource-sql/package.json
packages/datasource-sql/src/connection/index.ts
packages/datasource-sql/src/connection/reverse-proxy.ts
packages/datasource-sql/src/types.ts
packages/datasource-sql/test/connection/index.test.ts
packages/datasource-sql/test/connection/reverse-proxy.unit.test.ts

feat(datasource-sql): enable to proxify the tcp connection by a socks5 proxy

---

packages/datasource-sql/src/connection/index.ts
packages/datasource-sql/src/connection/preprocess.ts
packages/datasource-sql/src/connection/reverse-proxy.ts
packages/datasource-sql/src/index.ts
packages/datasource-sql/test/connection/index.test.ts
packages/datasource-sql/test/connection/reverse-proxy.unit.test.ts
packages/datasource-sql/test/datasource-factory.integration.test.ts

fix(ds-sql): force to close the proxy when closing sequelize instance. 

---

packages/datasource-sql/package.json

refactor(datasource-sql): remove unused dependency

---

packages/datasource-sql/src/connection/reverse-proxy.ts

fix(datasource-sql): do not crash at connection time when using proxy without providing port

---

packages/forestadmin-client/src/events-subscription/types.ts

refactor(forestadmin-client): updated interface [force release]

---

packages/datasource-sql/src/connection/errors.ts
packages/datasource-sql/src/connection/handle-errors.ts
packages/datasource-sql/src/connection/index.ts
packages/datasource-sql/src/connection/reverse-proxy.ts
packages/datasource-sql/src/connection/utils.ts
packages/datasource-sql/src/index.ts
packages/datasource-sql/test/connection/handle-errors.test.ts
packages/datasource-sql/test/connection/handle-errors.unit.test.ts
packages/datasource-sql/test/connection/index.test.ts
packages/datasource-sql/test/connection/utils.test.ts

refactor(connect): throw specific errors when a connection fails.

---

packages/datasource-sql/src/connection/index.ts
packages/datasource-sql/src/connection/utils.ts

refactor(datasource-sql): move getSslConfiguration function in the utils file [force release]

---

packages/agent/src/services/model-customizations/execute-webhook.ts
packages/agent/test/services/model-customizations/execute-webhook.test.ts

fix: improve errors from webhook endpoints

---

.eslintrc.js
packages/agent/src/agent.ts
packages/datasource-customizer/src/collection-customizer.ts

docs(agent): add links to relevant guide sections in inline doc

---

packages/datasource-sql/src/connection/handle-errors.ts
packages/datasource-sql/test/connection/handle-errors.unit.test.ts

fix(datasource-sql): improve the connect management errors

---

.github/workflows/build.yml

ci: add missing install step

---

package.json
yarn.lock

chore: bump all versions to latest minor

---

packages/datasource-sql/src/connection/connection-options.ts
packages/datasource-sql/test/connection/connection-options.test.ts

fix(datasource-sql): repair sqlite support

---

packages/datasource-customizer/src/context/relaxed-wrappers/collection.ts
packages/datasource-customizer/test/context/wrapper.test.ts

fix(customizer): validate fields on user facing collection interface

---

packages/agent/src/services/model-customizations/actions/update-record/update-record-plugin.ts
packages/agent/test/services/model-customizations/actions/update-record/update-record-plugin.test.ts
packages/forestadmin-client/src/model-customizations/types.ts

feat: handle field names containing underscores on update record actions

---

packages/datasource-sql/src/index.ts

fix(datasource-sql): export missing types

---

.github/workflows/build.yml

chore(ci): change build cache key

---

packages/datasource-sql/src/connection/connection-tester.ts
packages/datasource-sql/src/connection/index.ts
packages/datasource-sql/test/connection/connection-tester.test.ts

fix(datasource-sql): fix worker crash on authentication testing

---

packages/datasource-sql/src/connection/connection-options.ts

fix(datasource-sql): add proxy configuration when computing ssl

---

packages/_example/README.md

chore: add readme on example

---

packages/datasource-customizer/src/decorators/collection-decorator.ts

refactor(datasource-customizer): document unclear behavior

---

packages/agent/src/utils/csv-generator.ts
packages/agent/test/utils/csv-generator.test.ts

fix(agent): handle json field in csv export

---

packages/datasource-customizer/src/decorators/rename-field/collection.ts
packages/datasource-customizer/test/decorators/rename-field/collection.test.ts

fix(rename field decorator): throw when put space inside fieldName

---

packages/forestadmin-client/src/utils/server.ts
packages/forestadmin-client/test/utils/server.test.ts

fix: add a timeout on superagent call

---

packages/agent/src/services/model-customizations/actions/update-record/execute-update-record.ts
packages/agent/src/services/model-customizations/actions/update-record/update-record-plugin.ts
packages/agent/test/services/model-customizations/actions/update-record/execute-update-record.test.ts
packages/agent/test/services/model-customizations/actions/update-record/update-record-plugin.test.ts

feat(agent): no-code update record should handle errors correctly

---

packages/agent/src/utils/query-string.ts
packages/agent/test/routes/access/api-chart-collection.test.ts
packages/agent/test/routes/access/api-chart-datasource.test.ts
packages/agent/test/routes/access/chart.test.ts
packages/agent/test/routes/access/count-related.test.ts
packages/agent/test/routes/access/count.test.ts
packages/agent/test/routes/access/csv-related.test.ts
packages/agent/test/routes/access/csv.test.ts
packages/agent/test/routes/access/get.test.ts
packages/agent/test/routes/access/list-related.test.ts
packages/agent/test/routes/access/list.test.ts
packages/agent/test/routes/modification/action/action.test.ts
packages/agent/test/routes/modification/associate-related.test.ts
packages/agent/test/routes/modification/create.test.ts
packages/agent/test/routes/modification/delete-related.test.ts
packages/agent/test/routes/modification/delete.test.ts
packages/agent/test/routes/modification/dissociate-delete-related.test.ts
packages/agent/test/routes/modification/dissociate-related.test.ts
packages/agent/test/routes/modification/update-field.test.ts
packages/agent/test/routes/modification/update-relation.test.ts
packages/agent/test/routes/modification/update.test.ts
packages/agent/test/utils/query-string.test.ts
packages/datasource-toolkit/src/interfaces/caller.ts
packages/datasource-toolkit/test/__factories__/caller.ts

fix(agent): add request identifier to context.caller

---

packages/datasource-customizer/package.json
yarn.lock

fix(datasource-customizer): attempt to fix install when using latest nestjs version

---

packages/forestadmin-client/src/events-subscription/index.ts

refactor(client): change event source reconnect interval to 5 secondes

---

packages/forestadmin-client/src/events-subscription/index.ts
packages/forestadmin-client/test/events-subscription/index.test.ts

fix(client): handle more errors on Server Sent Event issues to better reflect what is going on

---

packages/agent/src/agent.ts
packages/agent/src/framework-mounter.ts
packages/agent/test/__factories__/forest-admin-client.ts
packages/agent/test/agent.test.ts
packages/forestadmin-client/src/events-subscription/index.ts
packages/forestadmin-client/src/events-subscription/types.ts
packages/forestadmin-client/src/forest-admin-client-with-cache.ts
packages/forestadmin-client/src/types.ts
packages/forestadmin-client/test/__factories__/events-subscription/index.ts
packages/forestadmin-client/test/events-subscription/index.test.ts
packages/forestadmin-client/test/forest-admin-client-with-cache.test.ts

refactor(client): allow to close gracefully the current event source

---

packages/datasource-customizer/src/decorators/computed/collection.ts
packages/datasource-customizer/src/decorators/rename-field/collection.ts
packages/datasource-customizer/test/collection-customizer.test.ts
packages/datasource-customizer/test/decorators/computed/collection.test.ts
packages/datasource-customizer/test/decorators/rename-field/collection.test.ts
packages/datasource-toolkit/src/validation/field.ts
packages/datasource-toolkit/test/validation/field/field.test.ts

fix(add field decorator): throw when put space inside fieldName

---

packages/agent/src/utils/forest-schema/generator.ts
packages/agent/test/agent.test.ts
packages/agent/test/utils/forest-schema/generator.test.ts
packages/forestadmin-client/src/schema/index.ts
packages/forestadmin-client/src/schema/types.ts
packages/forestadmin-client/test/forest-admin-client-with-cache.test.ts
packages/forestadmin-client/test/schema/index.test.ts

fix(agent): use meta instead of metadata in the schema

---

packages/forestadmin-client/package.json
packages/forestadmin-client/src/permissions/action-permission.ts
packages/forestadmin-client/src/permissions/rendering-permission.ts
packages/forestadmin-client/src/utils/ttl-cache.ts
packages/forestadmin-client/test/utils/ttl-cache.test.ts
yarn.lock

fix(forestadmin-client): crash with lru cache concurrent clear and fetch

---

packages/agent/src/utils/forest-schema/generator-fields.ts
packages/datasource-sql/src/introspection/helpers/sql-type-converter.ts

fix(agent): sort enum values to avoid versioning conflicts

---

packages/datasource-sequelize/src/collection.ts
packages/datasource-sequelize/src/utils/query-converter.ts
packages/datasource-sequelize/test/collection.test.ts
packages/datasource-sequelize/test/utils/query-converter.unit.test.ts

fix(datasource-sequelize): do not ignore deeply nested fields in projections

---

packages/agent/src/routes/modification/action/action.ts
packages/agent/src/services/authorization/types.ts
packages/agent/test/routes/modification/action/action.test.ts
packages/datasource-customizer/src/decorators/actions/collection.ts
packages/datasource-customizer/src/decorators/actions/context/base.ts
packages/datasource-customizer/test/decorators/actions/collection.test.ts
packages/datasource-toolkit/src/decorators/collection-decorator.ts
packages/datasource-toolkit/src/interfaces/collection.ts
packages/datasource-toolkit/test/decorators/collection-decorator.test.ts

feat: add changed field to action context

---

packages/_example/src/forest/customizations/account.ts
packages/_example/src/forest/customizations/card.ts
packages/_example/src/forest/customizations/comment.ts
packages/_example/src/forest/customizations/customer.ts
packages/_example/src/forest/customizations/dvd.ts
packages/_example/src/forest/customizations/owner.ts
packages/_example/src/forest/customizations/post.ts
packages/_example/src/forest/customizations/rental.ts
packages/_example/src/forest/customizations/review.ts
packages/_example/src/forest/customizations/store.ts
packages/_example/src/forest/typings.ts
packages/agent/src/index.ts
packages/datasource-customizer/src/typing-generator.ts
packages/datasource-customizer/test/typing-generator.test.ts

feat(datasource-customizer): generate typings aliases for easier use

---

packages/agent/src/agent.ts
packages/datasource-customizer/src/collection-customizer.ts

fix(datasource-customizer): fix addChart tsdoc

---

packages/_example/src/forest/customizations/dvd.ts
packages/datasource-customizer/src/context/relaxed-wrappers/collection.ts
packages/datasource-customizer/test/context/wrapper.test.ts
packages/datasource-mongoose/src/collection.ts
packages/datasource-sequelize/src/collection.ts
packages/datasource-sequelize/test/collection.test.ts
packages/datasource-toolkit/src/base-collection.ts
packages/datasource-toolkit/src/decorators/collection-decorator.ts
packages/datasource-toolkit/src/interfaces/collection.ts
packages/datasource-toolkit/test/__factories__/collection.ts
packages/datasource-toolkit/test/decorators/collection-decorator.test.ts

feat(datasource-customizer): expose native driver to customers

---

packages/datasource-replica/package.json

fix(replica): module not found error when importing the datasource-replica

---

packages/agent/src/utils/forest-schema/generator-action-field-widget.ts
packages/agent/src/utils/forest-schema/generator-actions.ts
packages/agent/test/utils/forest-schema/generator-action-field-widget.test.ts
packages/agent/test/utils/forest-schema/generator-actions.test.ts
packages/datasource-customizer/src/decorators/actions/types/fields.ts
packages/forestadmin-client/src/schema/types.ts

refactor: use the same format for static and dynamic fields [force release]

---

packages/datasource-customizer/src/decorators/actions/types/fields.ts
packages/datasource-toolkit/src/interfaces/action.ts
packages/forestadmin-client/src/schema/types.ts

feat: allow to use an array of values for dropdown options

---

.gitignore

chore: add vscode settings to gitignore

chore: add vscode settings to gitignore

---

packages/datasource-customizer/src/decorators/actions/types/fields.ts

#85yxm8nc0
Example actions for testing:
```ts
.addAction('Increase the rental price', {
scope: 'Bulk',
form: [
{
widget: 'Dropdown',
label: `number-list-search`,
type: 'NumberList',
placeholder: 'aasetaui',
options: [
{ value: 1, label: 'the one' },
{ value: 2, label: 'the two' },
],
search: 'static',
},
{
widget: 'Dropdown',
label: `StringList-search`,
type: 'StringList',
placeholder: 'aaaabbb',
options: [
{ value: '123', label: 'Hello !!!' },
{ value: 'tata', label: 'another' },
{ value: 'tatatata', label: 'another - tatata' },
{ value: 'and', label: 'toto' },
],
search: 'disabled',
},
]
),
```

feat: add support for stringList dropdown

---

packages/agent/src/utils/forest-schema/action-fields.ts
packages/agent/src/utils/forest-schema/generator-action-field-widget.ts
packages/agent/test/utils/forest-schema/generator-action-field-widget.test.ts
packages/datasource-customizer/src/decorators/actions/types/fields.ts
packages/datasource-toolkit/src/interfaces/action.ts
packages/forestadmin-client/src/schema/types.ts

feat: add support for the checkbox widget for boolean fields in smart actions

---

packages/datasource-customizer/src/decorators/actions/types/fields.ts
packages/datasource-toolkit/src/interfaces/action.ts
packages/forestadmin-client/src/schema/types.ts

fix(widgets): allow to use StringList type without a widget in smart actions

---

packages/agent/src/utils/forest-schema/action-fields.ts
packages/agent/src/utils/forest-schema/generator-action-field-widget.ts
packages/agent/test/utils/forest-schema/action-fields.test.ts
packages/agent/test/utils/forest-schema/generator-action-field-widget.test.ts
packages/datasource-customizer/src/decorators/actions/types/fields.ts
packages/datasource-toolkit/src/interfaces/action.ts
packages/forestadmin-client/src/schema/types.ts

feat(widgets): add support for TextInputList in smart actions

---

packages/agent/src/utils/forest-schema/action-fields.ts
packages/agent/src/utils/forest-schema/generator-action-field-widget.ts
packages/agent/test/utils/forest-schema/action-fields.test.ts
packages/agent/test/utils/forest-schema/generator-action-field-widget.test.ts
packages/datasource-customizer/src/decorators/actions/types/fields.ts
packages/datasource-toolkit/src/interfaces/action.ts
packages/forestadmin-client/src/schema/types.ts

feat(widgets): add support for textarea widget in custom actions

---

packages/agent/src/utils/forest-schema/action-fields.ts
packages/agent/src/utils/forest-schema/generator-action-field-widget.ts
packages/agent/test/utils/forest-schema/action-fields.test.ts
packages/agent/test/utils/forest-schema/generator-action-field-widget.test.ts
packages/datasource-customizer/src/decorators/actions/types/fields.ts
packages/datasource-toolkit/src/interfaces/action.ts
packages/forestadmin-client/src/schema/types.ts

feat(widgets): support rich text widget in custom actions

---

packages/agent/src/utils/forest-schema/action-fields.ts
packages/agent/src/utils/forest-schema/generator-action-field-widget.ts
packages/agent/test/utils/forest-schema/action-fields.test.ts
packages/agent/test/utils/forest-schema/generator-action-field-widget.test.ts
packages/datasource-customizer/src/decorators/actions/types/fields.ts
packages/datasource-toolkit/src/interfaces/action.ts
packages/forestadmin-client/src/schema/types.ts

feat(widgets): add support for the checkbox group widget in custom actions

---

yarn.lock

fix(security): patch mongodb dependency vulnerabilities

---

packages/agent/src/utils/forest-schema/action-fields.ts
packages/agent/src/utils/forest-schema/generator-action-field-widget.ts
packages/agent/test/utils/forest-schema/action-fields.test.ts
packages/agent/test/utils/forest-schema/generator-action-field-widget.test.ts
packages/datasource-customizer/src/decorators/actions/types/fields.ts
packages/datasource-toolkit/src/interfaces/action.ts
packages/forestadmin-client/src/schema/types.ts

feat(widgets): add support for number input in custom actions

---

.github/workflows/build.yml

chore: upgrade to checkout@v4

---

packages/agent/src/utils/forest-schema/action-fields.ts
packages/agent/src/utils/forest-schema/generator-action-field-widget.ts
packages/agent/test/utils/forest-schema/action-fields.test.ts
packages/agent/test/utils/forest-schema/generator-action-field-widget.test.ts
packages/datasource-customizer/src/decorators/actions/types/fields.ts
packages/datasource-toolkit/src/interfaces/action.ts
packages/forestadmin-client/src/schema/types.ts

feat(widgets): add support for number input lists with options in actions

---

packages/datasource-toolkit/src/utils/record.ts

fix(datasource-toolkit): return null instead of undefined inside field value getter

---

packages/datasource-mongoose/src/utils/pipeline/virtual-fields.ts
packages/datasource-mongoose/test/integration/flattener/collection_list.test.ts
packages/datasource-mongoose/test/utils/pipeline/virtual-fields.test.ts

fix(datasource-mongoose): return values instead of null when querying nested properties on a flattened field

---

packages/agent/src/utils/forest-schema/action-fields.ts
packages/agent/src/utils/forest-schema/generator-action-field-widget.ts
packages/agent/test/utils/forest-schema/action-fields.test.ts
packages/agent/test/utils/forest-schema/generator-action-field-widget.test.ts
packages/datasource-customizer/src/decorators/actions/types/fields.ts
packages/datasource-toolkit/src/interfaces/action.ts
packages/forestadmin-client/src/schema/types.ts

feat(widgets): add support for currency widget

---

packages/datasource-sql/src/introspection/introspector.ts
packages/datasource-sql/test/introspection/intropector.test.ts

fix(introspection): handle sqlite datasources in broken relationship logger

---

packages/datasource-replica/test/integrations/pull-delta.test.ts

test: fix randomly failing tests

---

.vscode/settings.json

chore: add some configuration to ease debugging with the jest plugin

---

packages/agent/src/routes/access/csv-related.ts
packages/agent/src/routes/access/list-related.ts
packages/agent/test/routes/access/csv-related.test.ts
packages/agent/test/routes/access/list-related.test.ts

fix(agent): fix related data access permissions

---

packages/datasource-customizer/src/decorators/actions/context/base.ts

fix: formValues type definition on action context

---

packages/agent/src/utils/forest-schema/action-fields.ts
packages/agent/src/utils/forest-schema/generator-action-field-widget.ts
packages/agent/test/utils/forest-schema/action-fields.test.ts
packages/agent/test/utils/forest-schema/generator-action-field-widget.test.ts
packages/datasource-customizer/src/decorators/actions/types/fields.ts
packages/datasource-toolkit/src/interfaces/action.ts
packages/forestadmin-client/src/schema/types.ts

feat(widgets): add support for the json editor widget in actions

---

packages/agent/src/routes/modification/update-relation.ts
packages/agent/test/routes/modification/update-relation.test.ts

fix: create records with a hasOne relationship and a notNull constraint without error

---

packages/datasource-customizer/src/decorators/actions/types/fields.ts

fix: allow dynamic description in smart action form fields

---

packages/datasource-customizer/src/decorators/actions/collection.ts
packages/datasource-customizer/test/decorators/actions/collection.test.ts

fix: prevent smart action from from being cleared on change hook

---

packages/datasource-customizer/src/decorators/actions/collection.ts
packages/datasource-customizer/test/decorators/actions/collection.test.ts

perf: do not send large files to apimap

---

packages/datasource-customizer/src/decorators/actions/collection.ts

refactor: improve search hook handling

---

packages/datasource-customizer/src/collection-customizer.ts
packages/datasource-customizer/src/types.ts

chore(datasource customizer): allow plugins use logger

---

packages/datasource-sql/src/index.ts
packages/datasource-sql/src/introspection/introspector.ts
packages/datasource-sql/src/introspection/type-overrides.ts
packages/datasource-sql/test/_helpers/setup-using-all-types.ts
packages/datasource-sql/test/_helpers/setup-using-relations.ts
packages/datasource-sql/test/datasource-factory.integration.test.ts
packages/datasource-sql/test/introspection/intropector.test.ts

fix: correctly detect relationships on PG

---

packages/agent/src/agent.ts
packages/datasource-customizer/src/datasource-customizer.ts
packages/datasource-customizer/src/typing-generator.ts
packages/datasource-customizer/test/typing-generator.test.ts

fix: error starting the server because of a too large string when generating typings

---

packages/agent/src/routes/base-route.ts
packages/agent/test/routes/access/api-chart-datasource.test.ts

fix(charts): 404 error when retrieving a chart with spaces in the name

---

packages/datasource-customizer/src/decorators/chart/result-builder.ts
packages/datasource-customizer/test/decorators/chart/result-builder.test.ts
packages/datasource-toolkit/src/interfaces/chart.ts

feat(chart): add multiple time based chart

---

packages/datasource-customizer/src/decorators/chart/result-builder.ts
packages/datasource-customizer/test/decorators/chart/result-builder.test.ts

fix(time-based-chart): don't crash when there is no value and format the data to display "no data" on the front

---

packages/agent/src/agent.ts
packages/agent/src/types.ts
packages/agent/src/utils/options-validator.ts
packages/agent/test/__factories__/forest-admin-http-driver-options.ts

fix(agent): add body parser options to allow increase body limits

---

packages/datasource-mongoose/src/collection.ts
packages/datasource-mongoose/src/utils/pipeline/as-model-not-null.ts
packages/datasource-mongoose/test/integration/flattener/_build-models.ts
packages/datasource-mongoose/test/integration/flattener/collection_list.test.ts

fix(datasource-mongoose): don't return records for null values of flattened fields when using asModel on object fields

---

packages/agent/src/routes/security/authentication.ts
packages/agent/test/__factories__/forest-admin-client.ts
packages/agent/test/routes/security/authentication.test.ts
packages/forestadmin-client/src/auth/errors.ts
packages/forestadmin-client/src/auth/index.ts
packages/forestadmin-client/src/auth/types.ts
packages/forestadmin-client/src/forest-admin-client-with-cache.ts
packages/forestadmin-client/src/index.ts
packages/forestadmin-client/src/types.ts
packages/forestadmin-client/test/auth/index.test.ts
packages/forestadmin-client/test/forest-admin-client-with-cache.test.ts

fix(authentication): return errors details during authentication instead of generic 500s

---

packages/forestadmin-client/src/auth/index.ts

refactor: declare the open id client as protected in the auth service [force release]

---

packages/forestadmin-client/src/build-application-services.ts
packages/forestadmin-client/src/forest-admin-client-with-cache.ts
packages/forestadmin-client/src/permissions/forest-http-api.ts
packages/forestadmin-client/src/types.ts
packages/forestadmin-client/test/__factories__/forest-admin-server-interface.ts

refactor: override the default auth service [force release]

---

packages/datasource-customizer/src/decorators/chart/result-builder.ts
packages/datasource-customizer/src/decorators/chart/types.ts
packages/datasource-customizer/test/decorators/chart/result-builder.test.ts

feat(charts): timebasedCharts: add option to display missing points as zeros

---

packages/datasource-mongoose/src/collection.ts
packages/datasource-mongoose/src/utils/add-null-values.ts
packages/datasource-mongoose/test/integration/many-to-one/collection_list.test.ts
packages/datasource-mongoose/test/integration/review/collection_list.test.ts
packages/datasource-mongoose/test/utils/add-null-values.test.ts

fix(datasource-mongoose): error on a nested field when requesting a child property on a missing value

---

packages/forestadmin-client/src/auth/index.ts
packages/forestadmin-client/test/auth/index.test.ts

fix(authentication): don't crash if an error occurs when initializing the authentication client

---

packages/datasource-customizer/src/decorators/chart/result-builder.ts
packages/datasource-customizer/src/decorators/chart/types.ts
packages/datasource-customizer/test/decorators/chart/result-builder.test.ts

[CU-860ry1f8a](https://app.clickup.com/t/860ry1f8a)

fix(charts): remove option to set zeros instead of null values & do it by default

---

packages/datasource-mongoose/src/utils/helpers.ts
packages/datasource-mongoose/test/utils/helper.test.ts

fix: support mangoose decimal128 type

---

packages/datasource-customizer/src/collection-customizer.ts
packages/datasource-customizer/src/datasource-customizer.ts
packages/datasource-customizer/src/templates.ts

fix(renameAndRemoveField): allow to rename or remove a relation by improving the TS typing

---

packages/datasource-sequelize/src/utils/error-handler.ts
packages/datasource-sequelize/test/utils/error-handler.test.ts

fix: send details to frontend on unexpected sequelize errors

---

packages/datasource-sql/src/introspection/introspector.ts
packages/datasource-sql/test/_helpers/connection-details.ts
packages/datasource-sql/test/_helpers/create-database-if-not-exist.ts
packages/datasource-sql/test/introspection/introspector.integration.test.ts
packages/datasource-sql/test/introspection/introspector.test.ts

fix: skip mssql tables with dots in their names instead of crashing the agent

---

packages/_example/package.json
packages/_example/src/forest/agent.ts
packages/_example/src/forest/typings.ts
packages/datasource-elasticsearch/package.json
packages/datasource-elasticsearch/src/introspection/introspector.ts
packages/datasource-elasticsearch/src/utils/type-converter.ts
packages/datasource-elasticsearch/tsconfig.json
yarn.lock

feat: initialize beta-datasource-elasticsearch

---

packages/datasource-customizer/src/collection-customizer.ts
packages/datasource-customizer/src/decorators/computed/types.ts
packages/datasource-customizer/test/collection-customizer.test.ts

fix(smart-field): log error on missing parameter dependencies and avoid crash

---

.github/workflows/build.yml
packages/datasource-elasticsearch/docker-compose.yml
packages/datasource-elasticsearch/src/collection.ts
packages/datasource-elasticsearch/test/collection.test.ts
packages/datasource-elasticsearch/test/datasource.unit.test.ts
packages/datasource-elasticsearch/test/helpers/connection-details.ts
packages/datasource-elasticsearch/test/helpers/elastic-search-index-manager.ts
packages/datasource-elasticsearch/test/introspection/builder.integration.test.ts
packages/datasource-elasticsearch/tsconfig.eslint.json

test: add integration test setup

---

packages/datasource-elasticsearch/src/introspection/builder.ts
packages/datasource-elasticsearch/test/helpers/elastic-search-template-manager.ts
packages/datasource-elasticsearch/test/introspection/builder.integration.test.ts

test(builder): add some integrations test to the datasource builder

---

packages/datasource-customizer/src/typing-generator.ts
packages/datasource-customizer/test/typing-generator.test.ts

fix: do not generate typing aliases with dashes

---

yarn.lock

fix(security): patch axios dependency vulnerabilities

---

packages/datasource-elasticsearch/src/collection.ts
packages/datasource-elasticsearch/src/datasource.ts
packages/datasource-elasticsearch/test/collection.test.ts

feat(datasource-elasticsearch): add native driver

---

packages/datasource-elasticsearch/src/collection.ts
packages/datasource-elasticsearch/src/utils/query-converter.ts

refactor: remove unused joins code for now

---

packages/datasource-elasticsearch/src/utils/query-converter.ts
packages/datasource-elasticsearch/test/utils/query-converter.integration.test.ts
packages/datasource-elasticsearch/test/utils/query-converter.unit.test.ts

fix: improve filter operators

---

packages/forestadmin-client/src/permissions/rendering-permission.ts
packages/forestadmin-client/test/permissions/rendering-permission.test.ts

fix: user receives 403 on newly created segment query

---

packages/datasource-customizer/src/typing-generator.ts
packages/datasource-customizer/test/typing-generator.test.ts

fix(typing): avoid ordering issues that causes issue with typing

---

packages/forestadmin-client/src/build-application-services.ts
packages/forestadmin-client/src/forest-admin-client-with-cache.ts
packages/forestadmin-client/src/types.ts
packages/forestadmin-client/test/__factories__/forest-admin-client-options.ts
packages/forestadmin-client/test/forest-admin-client-with-cache.test.ts

fix(restart): the agent should only restart when at least one customisation is installed

---

packages/agent/package.json
yarn.lock

fix(security): upgrade koa/cors to version 5

---

packages/datasource-customizer/src/typing-generator.ts
packages/datasource-customizer/test/typing-generator.test.ts

fix: quote typing keys in the generated typing file

---

packages/datasource-mongoose/src/index.ts

fix(mongoose): export mongoose options type

---

packages/datasource-sql/src/introspection/dialects/dialect.interface.ts
packages/datasource-sql/src/introspection/dialects/mssql-dialect.ts
packages/datasource-sql/src/introspection/dialects/mysql-dialect/index.ts
packages/datasource-sql/src/introspection/dialects/postgresql-dialect/index.ts
packages/datasource-sql/src/introspection/dialects/sqlite-dialect.ts
packages/datasource-sql/src/introspection/introspector.ts

refactor: move dialect specific logic

---

packages/agent/src/services/model-customizations/actions/update-record/update-record-plugin.ts
packages/agent/src/services/model-customizations/actions/webhook/webhook-plugin.ts
packages/agent/test/services/model-customizations/actions/update-record/update-record-plugin.test.ts
packages/agent/test/services/model-customizations/actions/webhook/webhook-plugin.test.ts
packages/agent/test/services/model-customizations/customization.test.ts
packages/datasource-customizer/src/datasource-customizer.ts
packages/datasource-customizer/test/datasource-customizer.test.ts

fix: cloud sync error with customization applied to missing collections

---

packages/datasource-customizer/src/collection-customizer.ts
packages/datasource-customizer/src/decorators/sort-emulate/collection.ts
packages/datasource-customizer/test/collection-customizer.test.ts
packages/datasource-customizer/test/decorators/sort-emulate/collection.test.ts

https://docs.forestadmin.com/developer-guide-agents-nodejs/agent-customization/fields/sort#disabling-sort

feat(customizer): allow users to disable sort properly on column

---

package.json

chore: define yarn version

---

packages/datasource-customizer/src/decorators/sort-emulate/collection.ts
packages/datasource-customizer/test/collection-customizer.test.ts
packages/datasource-customizer/test/decorators/sort-emulate/collection.test.ts

fix: disableFieldSorting is now only preventing frontend to sort the collection

---

packages/forestadmin-client/src/utils/server.ts
packages/forestadmin-client/test/utils/server.test.ts

fix: return more details in errors due to certificate validation to help debugging

---

packages/_example/src/forest/typings.ts

refactor(example): fix agent typings

---

.github/workflows/build.yml

refactor: bump nodejs version used in github actions

---

packages/cloud-toolkit/package.json

fix(cloud-toolkit): make it public

---

packages/cloud-toolkit/package.json

chore: add bin item

---

packages/cloud-toolkit/package.json
packages/cloud-toolkit/src/commands/main.ts

fix(cloud-toolkit): add node interpreter to be executed by the bin

---

.gitignore
packages/cloud-toolkit/index.js
packages/cloud-toolkit/package.json
yarn.lock

feat(cloud-toolkit): download customizer from main entry

---

packages/cloud-toolkit/package.json
packages/cloud-toolkit/src/commands/bootstrap.ts
packages/cloud-toolkit/src/commands/main.ts

fix(cloud-toolkit): fix bootstrap

---

packages/cloud-toolkit/package.json
yarn.lock

fix(cloud-toolkit): add sqlite as dependency

---

packages/cloud-toolkit/package.json

fix(cloud-toolkit): replace sqlite to sqlite3

---

packages/cloud-toolkit/newbootstrap/.env.test
packages/cloud-toolkit/package.json
packages/cloud-toolkit/src/command.ts
packages/cloud-toolkit/src/services/bootstrap.ts
packages/cloud-toolkit/src/services/update-typings.ts
yarn.lock

feat: improve console feedback

---

packages/cloud-toolkit/.env.example
packages/cloud-toolkit/package.json

fix(cloud-toolkit): bump agent again to fix the build

---

packages/cloud-toolkit/src/command.ts
packages/cloud-toolkit/src/errors.ts
packages/cloud-toolkit/src/services/environment-variables.ts
packages/cloud-toolkit/src/services/http-forest-server.ts

feat: improve error management

---

packages/cloud-toolkit/src/command.ts
packages/cloud-toolkit/src/services/action-runner.ts

fix(cloud-toolkit): reload env variable when auth token is re-fetched.

---

packages/cloud-toolkit/package.json
packages/cloud-toolkit/src/command.ts
packages/cloud-toolkit/src/services/bootstrap.ts
packages/cloud-toolkit/src/services/environment-variables.ts

refactor(cloud-toolkit): remove created files when the is an error during the bootstrap 

---

packages/cloud-toolkit/README.md

feat: add README

---

.releaserc.js

fix: release must be triggered when a branch start by beta- or alpha-

---

packages/cloud-toolkit/package.json
packages/cloud-toolkit/src/command.ts
packages/cloud-toolkit/src/index.ts
packages/cloud-toolkit/src/services/http-forest-server.ts
packages/cloud-toolkit/src/services/publish.ts
yarn.lock

feat: define a new command to publish

---

packages/cloud-toolkit/src/services/environment-variables.ts

feat(cloud-toolkit): allow cloud toolkit to login using application token for CI usages

---

packages/cloud-toolkit/package.json

fix(cloud-toolkit): make the export type work

---

packages/cloud-toolkit/package.json
packages/cloud-toolkit/src/command.ts
packages/cloud-toolkit/src/services/packager.ts
yarn.lock

feat: provide code package command

---

packages/cloud-toolkit/src/services/http-forest-server.ts

feat: use axios handler for error handling when getting last published code details

---

packages/cloud-toolkit/package.json
yarn.lock

fix(cloud-toolkit): bump forest-cli to fix oclif warning during installation 

---

packages/datasource-customizer/src/decorators/search/collection-search-context.ts
packages/datasource-customizer/src/decorators/search/collection.ts
packages/datasource-customizer/src/decorators/search/types.ts
packages/datasource-customizer/test/decorators/search/collections.test.ts
packages/datasource-toolkit/src/interfaces/query/condition-tree/nodes/base.ts
packages/datasource-toolkit/src/interfaces/query/condition-tree/nodes/branch.ts
packages/datasource-toolkit/src/interfaces/query/condition-tree/nodes/leaf.ts
packages/datasource-toolkit/test/__factories__/schema/column-schema.ts
packages/datasource-toolkit/test/interfaces/query/condition-tree/nodes/branch.test.ts

feat: add access to the default search in replaceSearch on a collection

---

packages/cloud-toolkit/src/services/packager.ts
packages/cloud-toolkit/src/services/publish.ts

fix(cloud-toolkit): fix packager path to be cross platform

---

packages/cloud-toolkit/src/services/action-runner.ts
packages/cloud-toolkit/test/services/action-runner.unit.test.ts

fix(cloud-toolkit): exit with code 1 when a business error is triggered to cancel commands

---

packages/cloud-toolkit/.env.example
packages/cloud-toolkit/package.json
packages/cloud-toolkit/src/command.ts
packages/cloud-toolkit/src/dialogs/ask-to-overwrite-customizations.ts
packages/cloud-toolkit/src/services/environment-variables.ts
packages/cloud-toolkit/src/services/event-subscriber.ts
packages/cloud-toolkit/src/services/publish.ts
packages/cloud-toolkit/src/types.ts
yarn.lock

feat(publis): listen to code customization events

---

packages/cloud-toolkit/src/services/http-forest-server.ts

refactor: remove dead code

---

packages/cloud-toolkit/src/dialogs/ask-to-overwrite-customizations.ts

fix: handle empty response on last publish details

---

packages/cloud-toolkit/src/command.ts
packages/cloud-toolkit/src/dialogs/ask-to-overwrite-customizations.ts

feat(cloud-toolkit): add an option to force to publish 

---

packages/cloud-toolkit/src/command.ts

fix(cloud-toolkit): rename publish to package

---

packages/cloud-toolkit/package.json

fix(cloud-toolkit): rename cloud-toolkit to forest-cloud

---

packages/datasource-customizer/src/decorators/search/collection-search-context.ts

fix(types): allow to use relationships in generateSearchFilter

---

packages/cloud-toolkit/src/command.ts
packages/cloud-toolkit/src/errors.ts
packages/cloud-toolkit/src/services/action-runner.ts
packages/cloud-toolkit/src/services/bootstrap.ts
packages/cloud-toolkit/src/services/packager.ts
packages/cloud-toolkit/src/services/update-typings.ts
packages/cloud-toolkit/src/templates/hello-world.txt

feat: use customization to deduce typings

---

packages/cloud-toolkit/test/services/publish.unit.test.ts

test: add coverage for publish service

---

packages/_example/src/forest/typings.ts
packages/datasource-replica/src/sequelize.ts
packages/datasource-sql/src/index.ts
packages/datasource-sql/src/introspection/introspector.ts
packages/datasource-sql/src/introspection/types.ts
packages/datasource-sql/test/datasource-factory.integration.test.ts
packages/datasource-sql/test/index.test.ts
packages/datasource-sql/test/introspection/introspector.integration.test.ts

feat: add version in introspection

---

packages/cloud-toolkit/src/services/update-typings.ts

fix: dont specify yarn

---

packages/cloud-toolkit/test/services/packager.unit.test.ts

test: add coverage for packager service

---

packages/cloud-toolkit/test/services/publish.unit.test.ts

fix: remove IDE linting issues caused by jest

---

.eslintrc.js
package.json
packages/agent/test/routes/modification/action/action.test.ts
packages/agent/test/services/model-customizations/actions/update-record/update-record-plugin.test.ts
packages/agent/test/services/model-customizations/actions/webhook/webhook-plugin.test.ts
packages/agent/test/utils/forest-schema/action-fields.test.ts
packages/agent/test/utils/forest-schema/generator-action-field-widget.test.ts
packages/datasource-customizer/test/datasource-customizer.test.ts
packages/datasource-customizer/test/decorators/actions/collection.test.ts
packages/datasource-customizer/test/decorators/computed/utils.test.ts
packages/datasource-customizer/test/decorators/search/filter-builder/build-number-field-filter.test.ts
packages/datasource-customizer/test/typing-generator.test.ts
packages/datasource-mongoose/test/utils/schema/fields_simple.test.ts
packages/datasource-mongoose/test/utils/schema/filter-operator.test.ts
packages/forestadmin-client/test/events-subscription/index.test.ts
packages/plugin-aws-s3/test/index.test.ts
yarn.lock

style: lint with jest formatter

---

packages/cloud-toolkit/src/services/event-subscriber.ts
packages/cloud-toolkit/test/services/event-subscriber.unit.test.ts

test: add coverage for event subscriber

---

packages/cloud-toolkit/src/command.ts
packages/cloud-toolkit/src/dialogs/action-runner.ts
packages/cloud-toolkit/src/make-commands.ts
packages/cloud-toolkit/src/types.ts
packages/cloud-toolkit/test/commands/bootstrap.test.ts
packages/cloud-toolkit/test/commands/command-tester.ts
packages/cloud-toolkit/test/commands/utils.ts
packages/cloud-toolkit/test/services/action-runner.unit.test.ts

test: add spinner mock

---

packages/cloud-toolkit/.eslintrc.js
packages/cloud-toolkit/test/commands/command-tester.ts

fix(cloud-toolkit): remove console log

---

packages/cloud-toolkit/src/services/environment-variables.ts
packages/cloud-toolkit/test/commands/login.test.ts
packages/cloud-toolkit/test/commands/utils.ts

test: test login command

---

packages/cloud-toolkit/src/command.ts
packages/cloud-toolkit/src/dialogs/action-runner.ts
packages/cloud-toolkit/src/dialogs/ask-to-overwrite-customizations.ts
packages/cloud-toolkit/src/login.ts
packages/cloud-toolkit/src/make-commands.ts
packages/cloud-toolkit/src/services/bootstrap-path-manager.ts
packages/cloud-toolkit/src/services/bootstrap.ts
packages/cloud-toolkit/src/services/environment-variables.ts
packages/cloud-toolkit/src/types.ts
packages/cloud-toolkit/test/commands/bootstrap.test.ts
packages/cloud-toolkit/test/commands/command-tester.ts
packages/cloud-toolkit/test/commands/utils.ts
packages/cloud-toolkit/test/services/action-runner.unit.test.ts
packages/cloud-toolkit/test/services/bootstrap.unit.test.ts

test: add happy path to bootstrap 

---

packages/cloud-toolkit/src/services/environment-variables.ts
packages/cloud-toolkit/test/commands/login.test.ts
packages/cloud-toolkit/test/services/environment-variables.unit.test.ts

test: unit test environment variables

---

packages/cloud-toolkit/test/services/event-subscriber.unit.test.ts
packages/cloud-toolkit/test/services/publish.unit.test.ts

test: increase coverage EventSubscriber & publish

---

packages/cloud-toolkit/src/make-commands.ts
packages/cloud-toolkit/src/services/bootstrap-path-manager.ts
packages/cloud-toolkit/src/services/bootstrap.ts
packages/cloud-toolkit/src/services/packager.ts
packages/cloud-toolkit/src/services/update-typings.ts
packages/cloud-toolkit/test/commands/package.test.ts
packages/cloud-toolkit/test/commands/update-typings.test.ts
packages/cloud-toolkit/test/services/bootstrap.unit.test.ts
packages/cloud-toolkit/test/services/update-typings.unit.test.ts

fix: add test for update-typings and fix package message on error

---

packages/cloud-toolkit/src/services/access-file.ts
packages/cloud-toolkit/src/services/packager.ts
packages/cloud-toolkit/src/services/update-typings.ts
packages/cloud-toolkit/test/commands/package.test.ts
packages/cloud-toolkit/test/services/packager.unit.test.ts
packages/cloud-toolkit/test/services/update-typings.unit.test.ts

fix: refactor error to have the same message when build is not found

---

packages/cloud-toolkit/src/services/http-server.ts
packages/cloud-toolkit/test/services/http-server.unit.test.ts

test: add unit test to http server service

---

packages/cloud-toolkit/test/services/environment-variables.unit.test.ts
packages/cloud-toolkit/test/services/http-server.unit.test.ts

style: fix test line padding

---

packages/cloud-toolkit/src/services/bootstrap-path-manager.ts
packages/cloud-toolkit/src/services/bootstrap.ts
packages/cloud-toolkit/test/services/bootstrap.unit.test.ts
packages/cloud-toolkit/test/services/environment-variables.unit.test.ts

test: improve coverage

---

packages/cloud-toolkit/test/services/update-typings.unit.test.ts

fix: improve path dependent tests

---

packages/cloud-toolkit/src/services/bootstrap.ts
packages/cloud-toolkit/src/templates/hello-world.txt
packages/cloud-toolkit/test/services/bootstrap.unit.test.ts

feat: remove unneeded hello world

---

packages/cloud-toolkit/src/services/bootstrap-path-manager.ts
packages/cloud-toolkit/src/services/update-typings.ts
packages/cloud-toolkit/test/commands/update-typings.test.ts
packages/cloud-toolkit/test/services/update-typings.unit.test.ts

fix: typings path is not correct during bootstrap

---

packages/cloud-toolkit/src/dialogs/action-runner.ts
packages/cloud-toolkit/test/build-commands.test.ts
packages/cloud-toolkit/test/commands/utils.ts
packages/cloud-toolkit/test/services/action-runner.unit.test.ts

fix: when chaining commands, the process must exist if fails

---

packages/agent/src/agent.ts
packages/agent/test/agent.test.ts

feat: use the agent to create typings

---

packages/_example/CHANGELOG.md
packages/_example/package.json
packages/_example/src/forest/typings.ts
packages/agent/CHANGELOG.md
packages/agent/package.json
yarn.lock

refactor: bump merge main

---

yarn.lock

refactor: merge yarn lock to avoid conflict

---

packages/forest-cloud/package.json

fix(forest-cloud): add json files in the project dependencies

---

packages/forest-cloud/package.json
yarn.lock

fix(forest-cloud): bump forest-cli to remove warning during installation

---

packages/datasource-sequelize/docker-compose.yml
packages/datasource-sql/docker-compose.yml

chore: fix mariadb CI issue

---

packages/forest-cloud/src/commands/bootstrap.ts
packages/forest-cloud/src/services/bootstrap.ts
packages/forest-cloud/src/services/environment-variables.ts
packages/forest-cloud/src/types.ts
packages/forest-cloud/test/commands/bootstrap.test.ts
packages/forest-cloud/test/services/bootstrap.unit.test.ts
packages/forest-cloud/test/services/environment-variables.unit.test.ts

feat: dump non default passed env variables to .env

---

packages/forest-cloud/src/commands/bootstrap.ts
packages/forest-cloud/src/services/bootstrap-path-manager.ts
packages/forest-cloud/src/services/bootstrap.ts
packages/forest-cloud/test/commands/bootstrap.test.ts
packages/forest-cloud/test/commands/utils.ts
packages/forest-cloud/test/services/bootstrap.unit.test.ts

feat(forest-cloud): allow the user to give a name of his project

---

packages/_example/src/forest/typings.ts
packages/datasource-sequelize/test/integration/list/filter.integration.test.ts

chore: fix the typings in example pacakge and remove an useless await

---

packages/forest-cloud/src/commands/bootstrap.ts
packages/forest-cloud/test/commands/bootstrap.test.ts

fix: name must be required for bootstrap command

---

packages/datasource-sql/src/orm-builder/model.ts
packages/datasource-sql/test/_helpers/connection-details.ts
packages/datasource-sql/test/datasource-factory.integration.test.ts
packages/datasource-sql/test/orm-builder/model.test.ts

fix: record creation with UUIDs on MySQL and MariaDB

---

packages/forest-cloud/src/commands/login.ts
packages/forest-cloud/src/login.ts
packages/forest-cloud/src/services/environment-variables.ts
packages/forest-cloud/src/shared.ts
packages/forest-cloud/src/types.ts
packages/forest-cloud/test/login.unit.test.ts
packages/forest-cloud/test/services/environment-variables.unit.test.ts

fix(forest-cloud): when login fails it displays a success message

---

packages/datasource-replica/src/cache-interface/datasource.ts
packages/datasource-toolkit/src/interfaces/caller.ts
packages/datasource-toolkit/test/__factories__/caller.ts

fix(caller): caller now exposes permissionLevel

---

packages/datasource-customizer/src/decorators/actions/result-builder.ts
packages/datasource-customizer/test/decorators/actions/result-builder.test.ts

fix(agent): action default success message is now handled by the frontend

---

packages/forest-cloud/package.json
packages/forest-cloud/src/build-commands.ts
packages/forest-cloud/src/commands/bootstrap.ts
packages/forest-cloud/src/commands/logs.ts
packages/forest-cloud/src/commands/version.ts
packages/forest-cloud/src/logger.ts
packages/forest-cloud/src/login.ts
packages/forest-cloud/src/make-commands.ts
packages/forest-cloud/src/services/environment-variables.ts
packages/forest-cloud/src/services/http-server.ts
packages/forest-cloud/src/shared.ts
packages/forest-cloud/src/types.ts
packages/forest-cloud/test/commands/bootstrap.test.ts
packages/forest-cloud/test/commands/command-tester.ts
packages/forest-cloud/test/commands/login.test.ts
packages/forest-cloud/test/commands/logs.test.ts
packages/forest-cloud/test/commands/package.test.ts
packages/forest-cloud/test/commands/publish.test.ts
packages/forest-cloud/test/commands/testers.ts
packages/forest-cloud/test/commands/update-typings.test.ts
packages/forest-cloud/test/commands/utils.ts
packages/forest-cloud/test/commands/version.test.ts
packages/forest-cloud/test/logger.unit.test.ts
packages/forest-cloud/test/login.unit.test.ts
packages/forest-cloud/test/services/http-server.unit.test.ts

feat(forest-cloud): add logs command to display logs

---

yarn.lock

fix(security): patch es5-ext dependency vulnerabilities

---

packages/forest-cloud/src/commands/logs.ts
packages/forest-cloud/test/commands/logs.test.ts

fix(logs): improve default message when nos logs are displayed

---

packages/forest-cloud/package.json
yarn.lock

fix: vulnerability in axios

---

packages/forest-cloud/package.json
yarn.lock

fix(security): patch jsonwebtoken dependency vulnerabilities

---

packages/forest-cloud/src/commands/logs.ts
packages/forest-cloud/test/commands/logs.test.ts

fix(logs): fix the wording when fetching logs

---

packages/datasource-sequelize/src/collection.ts

fix: clarify rawQuery only support sequelize replacements

---

packages/forest-cloud/src/commands/publish.ts
packages/forest-cloud/test/commands/publish.test.ts

fix: improve publish message wording

---

packages/datasource-sequelize/src/collection.ts
packages/datasource-sequelize/test/collection.test.ts

feat: allow rawQuery to use bind parameters

---

packages/forest-cloud/src/commands/bootstrap.ts
packages/forest-cloud/src/commands/publish.ts
packages/forest-cloud/src/dialogs/ask-question.ts
packages/forest-cloud/src/dialogs/ask-to-overwrite-customizations.ts
packages/forest-cloud/src/dialogs/display-customization-info.ts
packages/forest-cloud/src/services/http-server.ts
packages/forest-cloud/src/shared.ts
packages/forest-cloud/src/types.ts
packages/forest-cloud/test/commands/bootstrap.test.ts
packages/forest-cloud/test/commands/publish.test.ts

linked to: CU-86bxvu5k3
linked to: CU-86bxvupjf

fix(forest-cloud): improve wording when re-bootstrapping or publishing

---

packages/datasource-customizer/src/decorators/computed/types.ts
packages/datasource-customizer/test/collection-customizer.test.ts

fix: addField dependencies are mandatory

---

packages/forest-cloud/src/services/environment-variables.ts
packages/forest-cloud/test/services/environment-variables.unit.test.ts

feat: build FOREST_SUBSCRIPTION_URL from FOREST_SERVER_URL if needed

---

packages/forest-cloud/src/commands/logs.ts

fix(logs): add missing debug level

---

packages/datasource-customizer/src/collection-customizer.ts
packages/datasource-customizer/src/decorators/computed/types.ts
packages/datasource-customizer/src/decorators/computed/utils/map-deprecated.ts
packages/datasource-customizer/test/collection-customizer.test.ts
packages/datasource-customizer/test/decorators/computed/utils.test.ts
packages/datasource-customizer/test/decorators/search/filter-builder/index.test.ts
packages/datasource-toolkit/src/interfaces/schema.ts
packages/datasource-toolkit/src/validation/rules.ts

fix: addField is marked as deprecated by webstorm

---

packages/forest-cloud/src/services/update-typings.ts
packages/forest-cloud/test/services/update-typings.unit.test.ts

fix(forest-cloud): remove a deprecated warning when updating the typing

---

.vscode/settings.json

chore: fix eslint settings in vscode

---

packages/datasource-mongo/src/introspection/structure.ts
packages/datasource-mongo/test/introspection/structure.unit.test.ts

fix(datasource-mongo): auto introspection does not work

---

.releaserc.js

chore: allow more force release rules

---

packages/datasource-mongo/src/index.ts
packages/datasource-mongo/src/introspection/introspector.ts
packages/datasource-mongo/src/types.ts

refactor: expose connection params [force release]

---

packages/datasource-mongo/src/index.ts
packages/datasource-mongo/src/introspection/list-collections-from-introspection.ts
packages/datasource-mongo/test/introspection/list-collections-from-introspection.unit.test.ts
packages/datasource-sql/src/index.ts
packages/datasource-sql/src/introspection/list-collections-from-introspection.ts
packages/datasource-sql/test/introspection/list-collections-from-introspection.unit.test.ts

feat: list collections from an introspection result

---

packages/datasource-sql/src/introspection/introspector.ts
packages/datasource-sql/test/introspection/introspector.integration.test.ts

fix(sql): users should be able to use table with multiple sequences

---

.vscode/settings.json
packages/datasource-mongo/src/introspection/introspector.ts
packages/datasource-mongo/test/introspection/introspector.unit.test.ts

fix(mongo): introspection of models with more than 30 properties (by default)

---

.vscode/settings.json
packages/datasource-sql/src/introspection/list-collections-from-introspection.ts

fix(sql): fix the type of listCollectionsFromIntrospection to support previous versions of introspection

---

.github/workflows/build.yml

chore: use docker compose instead of docker-compose in CI

---

.github/workflows/build.yml
packages/datasource-sql/src/introspection/dialects/postgresql-dialect/index.ts
packages/datasource-sql/src/introspection/helpers/sql-type-converter.ts
packages/datasource-sql/test/introspection/dialects/dialects.integration.test.ts
packages/datasource-sql/test/introspection/helpers/sql-type-converter.test.ts

fix(sql): random error on postgresql during introspection caused by left join on information_schema.element_types

---

packages/datasource-sql/src/introspection/dialects/postgresql-dialect/index.ts
packages/datasource-sql/test/introspection/helpers/sql-type-converter.integration.test.ts

fix(sql): type detection for enums in schemas

---

packages/datasource-sql/src/index.ts

fix: replace latesIntrospection to legacyIntrospection

---

packages/datasource-sql/src/index.ts
packages/datasource-sql/src/introspection/introspector.ts
packages/datasource-sql/src/introspection/list-collections-from-introspection.ts
packages/datasource-sql/src/introspection/types.ts
packages/datasource-sql/src/orm-builder/model.ts
packages/datasource-sql/src/orm-builder/relations.ts
packages/datasource-sql/test/introspection/list-collections-from-introspection.unit.test.ts

fix: change introspection type to avoid breaking change

---

packages/datasource-customizer/src/collection-customizer.ts
packages/datasource-customizer/src/decorators/decorators-stack.ts
packages/datasource-customizer/src/decorators/override/collection.ts
packages/datasource-customizer/src/decorators/override/context.ts
packages/datasource-customizer/src/decorators/override/types.ts
packages/datasource-customizer/src/index.ts
packages/datasource-customizer/test/collection-customizer.test.ts
packages/datasource-customizer/test/decorators/override/collection.test.ts

feat(datasource-customizer): add override decorator

---

packages/forest-cloud/src/services/publish.ts
packages/forest-cloud/test/commands/publish.test.ts
packages/forest-cloud/test/services/latest-version.integration.test.ts
packages/forest-cloud/test/services/publish.unit.test.ts

fix(forest-cloud): display an error on upload errors

---

packages/datasource-mongo/src/introspection/introspector.ts
packages/datasource-sql/src/introspection/introspector.ts
packages/datasource-toolkit/src/errors.ts
packages/datasource-toolkit/test/errors.test.ts
packages/forest-cloud/package.json
packages/forest-cloud/src/services/update-typings.ts
packages/forest-cloud/test/services/update-typings.unit.test.ts
yarn.lock

fix: improve error message in the case of outdated introspection

---

packages/forestadmin-client/src/utils/server.ts
packages/forestadmin-client/test/utils/server.test.ts

fix: spacing in error message

---

packages/agent/src/routes/security/authentication.ts
packages/agent/test/routes/security/authentication.test.ts
packages/forestadmin-client/src/auth/errors.ts
packages/forestadmin-client/src/utils/server.ts
packages/forestadmin-client/test/utils/server.test.ts

feat: improve forbidden error handling

---

packages/agent/src/framework-mounter.ts
packages/agent/test/framework-mounter.test.ts

fix: wait the server to be closed when calling agent.close

---

packages/forest-cloud/package.json
yarn.lock

fix(security): patch mysql2 dependency vulnerabilities

---

packages/datasource-mongo/test/index.ssh.integration.test.ts

test: fix tests

---

packages/datasource-mongoose/src/mongoose/schema.ts
packages/datasource-mongoose/src/utils/options.ts
packages/datasource-mongoose/test/integration/flattener/_build-models.ts
packages/datasource-mongoose/test/integration/flattener/collection_create.test.ts
packages/datasource-mongoose/test/utils/options.integration.test.ts

fix(mongoose): max call stack size error when using auto flattening with empty property names

---

packages/datasource-mongoose/src/utils/helpers.ts
packages/datasource-mongoose/test/integration/flattener/collection_create.test.ts

fix(mongoose): error when applying auto flattening on deeply nested collections

---

packages/datasource-mongoose/src/collection.ts
packages/datasource-mongoose/src/utils/pipeline/filter.ts
packages/datasource-mongoose/src/utils/pipeline/lookup.ts
packages/datasource-mongoose/test/integration/many-to-one/collection_list.test.ts
packages/datasource-mongoose/test/utils/pipeline/filter.test.ts
packages/datasource-mongoose/test/utils/pipeline/lookup.test.ts

perf(mongoose): speed up queries with relationships by filtering before retrieving relations

---

yarn.lock

fix(security): patch ejs dependency vulnerabilities

---

packages/forestadmin-client/src/index.ts

chore: export functions to use it in the cloud context [force-release]

---

yarn.lock

fix(security): patch ws dependency vulnerabilities

---

packages/datasource-sql/src/introspection/list-collections-from-introspection.ts
packages/datasource-sql/test/introspection/list-collections-from-introspection.unit.test.ts

fix: views should be present in the list of collections

---

packages/datasource-mongo/src/introspection/structure.ts
packages/datasource-mongo/src/introspection/types.ts
packages/datasource-mongo/src/odm-builder/index.ts
packages/datasource-mongo/src/version-manager.ts
packages/datasource-mongo/test/introspection/structure.unit.test.ts
packages/datasource-mongo/test/odm-builder.unit.test.ts
packages/datasource-mongo/test/version-manager.unit.test.ts

fix(mongo): mongo datasource throws an error during introspection with mongoose 6 as dependency

---

packages/forest-cloud/src/services/event-subscriber.ts
packages/forest-cloud/test/services/event-subscriber.unit.test.ts

fix(forest-cloud): error after publishing a code customization

---

packages/datasource-customizer/src/collection-customizer.ts

docs(override): improve documentation for override create/delete/update

---

packages/agent/src/routes/system/error-handling.ts
packages/agent/test/routes/system/error-handling.test.ts
packages/datasource-toolkit/src/errors.ts

refactor(errors): add more native business errors

---

packages/datasource-mongoose/src/utils/pipeline/reparent.ts
packages/datasource-mongoose/test/utils/pipeline/reparent.test.ts

fix(documentDB): prevent field addition from flattener to exceed 30 fields to meet with DocumentDB limitation

---

packages/datasource-customizer/src/decorators/override/collection.ts
packages/datasource-customizer/test/decorators/override/collection.test.ts

fix(override-create): clean returned records by removing unknown fields

---

packages/datasource-sequelize/src/utils/query-converter.ts
packages/datasource-sequelize/test/integration/list/filter.integration.test.ts
packages/datasource-sequelize/test/utils/query-converter.unit.test.ts

fix: get rid of 'ambiguous column name' error when searching on collection with relationships

---

packages/datasource-toolkit/README.md

fix: force release the datasource-toolkit to fix exported types

---

packages/datasource-sequelize/src/utils/un-ambigous.ts
packages/datasource-sequelize/test/utils/un-ambigous.test.ts

fix(query converter): handle already safe fields

---

packages/agent/src/routes/system/error-handling.ts
packages/agent/test/routes/system/error-handling.test.ts
packages/datasource-toolkit/src/errors.ts

fix(errors): prevent error information leak and guaranty cross packages instanceof errors

---

packages/datasource-toolkit/src/validation/type-getter.ts
packages/datasource-toolkit/test/validation/field/number.test.ts
packages/datasource-toolkit/test/validation/type-getter.test.ts

fix(validation): support bigint format

---

packages/plugin-aws-s3/src/utils/s3.ts
packages/plugin-aws-s3/test/index.test.ts

#86bzn5pe6
occurs with 
acl: 'public-read', or
acl: 'public-read-write',

fix: s3 plugin not correctly displaying images

---

packages/forest-cloud/src/commands/logs.ts
packages/forest-cloud/test/commands/logs.test.ts

…s" message at
the end
linked to: CU-86bzuwm5x

feat(cli-cloud): when tail option is given does not display "more logs" message at the end

---

packages/datasource-customizer/src/decorators/actions/collection.ts
packages/datasource-customizer/src/decorators/actions/types/actions.ts
packages/datasource-customizer/test/decorators/actions/collection.test.ts

feat(action): allow dynamic form

---

packages/datasource-customizer/src/collection-customizer.ts

fix: update outdated links in jsdoc

---

yarn.lock

fix(security): patch fast-xml-parser dependency vulnerabilities

---

packages/datasource-sequelize/src/utils/un-ambigous.ts
packages/datasource-sequelize/test/utils/un-ambigous.test.ts

fix(query-converter): handle renamed sequelize fields

---

packages/datasource-customizer/src/context/agent-context.ts
packages/datasource-customizer/src/decorators/hook/context/hook.ts

feat: make throw error function available in all customization context

---

packages/datasource-sequelize/src/utils/aggregation.ts
packages/datasource-sequelize/test/integration/aggregation/count.integration.test.ts

fix: records count supports sequelize alias minifying

---

packages/datasource-sql/src/orm-builder/model.ts

fix(datasource-sql): handle timestamps of tables with underscored column names

---

packages/agent/test/utils/forest-schema/generator-fields_many-to-many.test.ts
packages/agent/test/utils/query-string.test.ts
packages/datasource-sequelize/src/utils/model-to-collection-schema-converter.ts
packages/datasource-toolkit/src/interfaces/query/sort/factory.ts
packages/datasource-toolkit/test/__factories__/schema/column-schema.ts
packages/datasource-toolkit/test/interfaces/sort.test.ts

fix: default sorting behaviour prevent sorting on unsortable fields

---

packages/datasource-sql/src/orm-builder/model.ts

Reverts ForestAdmin/agent-nodejs#1165

revert:  "fix(datasource-sql): handle timestamps of tables with underscored column names"

---

packages/datasource-sequelize/src/utils/model-to-collection-schema-converter.ts
packages/datasource-sequelize/test/utils/model-to-collection-schema-converter.test.ts
packages/datasource-sql/test/_helpers/connection-details.ts

fix(sequelize): model validation should handle correctly is validator

---

packages/agent/src/routes/modification/dissociate-delete-related.ts
packages/agent/test/routes/modification/delete-related.test.ts
packages/agent/test/routes/modification/dissociate-delete-related.test.ts
packages/agent/test/routes/modification/dissociate-related.test.ts

fix(permissions): properly check permissions when dissociating or deleting related resources

---

packages/plugin-export-advanced/src/index.ts
packages/plugin-export-advanced/test/index.test.ts

fix(advanced-export): export now uses context.filter

---

packages/datasource-customizer/src/decorators/actions/collection.ts
packages/datasource-customizer/test/decorators/actions/collection.test.ts

[Ticket #86c0v8uju](https://app.clickup.com/t/86c0v8uju)

fix: change error message when mixing pages and other elements in an action form

---

packages/forest-cloud/src/commands/bootstrap.ts
packages/forest-cloud/test/commands/bootstrap.test.ts

fix(typo): bootstrap command

---

packages/_example/package.json
packages/datasource-replica/package.json
packages/datasource-sequelize/package.json
packages/datasource-sql/package.json
packages/forest-cloud/package.json
yarn.lock

chore: upgrade sequelize to v6.37.5

---

package.json
yarn.lock

fix(security): patch express dependency vulnerabilities

---

packages/datasource-mongo/docker-compose.yml
packages/datasource-sql/docker-compose.yml

ci: fix openssh-server version to prevent permission issue on config

---

packages/agent/src/routes/capabilities.ts
packages/agent/test/routes/capabilities.test.ts
packages/datasource-customizer/src/decorators/composite-datasource.ts
packages/datasource-customizer/test/decorators/composite-datasource.test.ts
packages/datasource-customizer/test/decorators/decorators-stack-no-code.unit.test.ts
packages/datasource-customizer/test/decorators/decorators-stack.unit.test.ts
packages/datasource-sequelize/src/datasource.ts
packages/datasource-sequelize/src/index.ts
packages/datasource-sequelize/src/types.ts
packages/datasource-sequelize/test/datasource.unit.test.ts
packages/datasource-sql/src/index.ts
packages/datasource-sql/src/types.ts
packages/datasource-sql/test/index.test.ts
packages/datasource-toolkit/src/base-datasource.ts
packages/datasource-toolkit/src/decorators/datasource-decorator.ts
packages/datasource-toolkit/src/interfaces/collection.ts
packages/datasource-toolkit/test/__factories__/datasource.ts
packages/datasource-toolkit/test/base-datasource.test.ts
packages/datasource-toolkit/test/decorators/datasource-decorator.test.ts

Reverts ForestAdmin/agent-nodejs#1211

revert:  chore(capabilities): define native query connection capabilities

---

packages/agent/src/routes/capabilities.ts
packages/agent/test/routes/capabilities.test.ts
packages/datasource-customizer/src/decorators/composite-datasource.ts
packages/datasource-customizer/test/decorators/composite-datasource.test.ts
packages/datasource-customizer/test/decorators/decorators-stack-no-code.unit.test.ts
packages/datasource-customizer/test/decorators/decorators-stack.unit.test.ts
packages/datasource-sequelize/src/datasource.ts
packages/datasource-sequelize/src/index.ts
packages/datasource-sequelize/src/types.ts
packages/datasource-sequelize/test/datasource.unit.test.ts
packages/datasource-sql/src/index.ts
packages/datasource-sql/src/types.ts
packages/datasource-sql/test/index.test.ts
packages/datasource-toolkit/src/base-datasource.ts
packages/datasource-toolkit/src/decorators/datasource-decorator.ts
packages/datasource-toolkit/src/interfaces/collection.ts
packages/datasource-toolkit/test/__factories__/datasource.ts
packages/datasource-toolkit/test/base-datasource.test.ts
packages/datasource-toolkit/test/decorators/datasource-decorator.test.ts

Re-release of #1211  using `feat` tag to release all packages.

feat(capabilities): define native query connection capabilities

---

packages/agent/src/routes/capabilities.ts
packages/agent/test/routes/capabilities.test.ts

feat(capabilities): add capabilities on get one projection

---

packages/agent/src/routes/capabilities.ts
packages/agent/test/routes/capabilities.test.ts

fix: introduce agentCapabilities sub object

---

packages/_example/src/connections/sequelize-postgres.ts
packages/datasource-sequelize/src/collection.ts
packages/datasource-sequelize/test/collection.test.ts

fix(sequelize-ds): allow user to create a record when there is a virtual field by removing it from the returned record

---

yarn.lock

fix(security): patch mongoose dependency vulnerabilities

---

packages/_example/package.json
yarn.lock

chore: update tedious to build on node 22

---

packages/agent/package.json
packages/datasource-customizer/package.json
packages/datasource-toolkit/package.json
yarn.lock

feat: upgrade uuid package to handle uuid v7

---

packages/datasource-customizer/src/decorators/lazy-join/collection.ts
packages/datasource-customizer/test/decorators/lazy-join/collection.test.ts

fix(lazy join): do not remove foreignkey when they are asking

---

packages/datasource-toolkit/src/validation/rules.ts
packages/datasource-toolkit/test/validation/condition-tree/boolean.test.ts
packages/datasource-toolkit/test/validation/condition-tree/date.test.ts
packages/datasource-toolkit/test/validation/condition-tree/number.test.ts
packages/datasource-toolkit/test/validation/condition-tree/string.test.ts

fix(validator): allow null value for Equal operator

---

packages/forest-cloud/src/services/bootstrap.ts
packages/forest-cloud/test/services/bootstrap.unit.test.ts

fix(forest-cloud): show stack trace for business errors during bootstrap

---

packages/agent/src/routes/access/chart.ts
packages/agent/test/routes/access/chart.test.ts

fix(charts): properly format week of year

---

.github/workflows/build.yml

chore(ci): fix publish api reference step

---

packages/_example/package.json
packages/agent/package.json
yarn.lock

fix(vulnerability): fix critical vulnerability on koa

---

.github/workflows/build.yml
packages/forest-cloud/test/services/action-runner.unit.test.ts
yarn.lock

ci: try to fix mongoose tests

---

packages/datasource-mongoose/src/collection.ts
packages/datasource-mongoose/src/utils/pipeline/filter.ts
packages/datasource-mongoose/test/utils/pipeline/filter.test.ts

fix: belongs to typeahead does not return correct values

---

packages/datasource-sql/src/orm-builder/model.ts
packages/datasource-sql/test/orm-builder/model.test.ts

fix: display deletedAt field when no timestamp are setup

---

.github/workflows/build.yml

ci: try to fix github page publish

---

.github/workflows/build.yml

ci: try to fix github page publish again

---

packages/agent/src/routes/capabilities.ts
packages/agent/test/routes/capabilities.test.ts
packages/datasource-toolkit/src/index.ts
packages/datasource-toolkit/src/validation/type-getter.ts
packages/datasource-toolkit/test/validation/type-getter.test.ts

fix(capabilities): should only handle Primitive type fields

---

packages/forest-cloud/package.json
yarn.lock

linked to: https://app.clickup.com/t/86c2mux6z

fix(forest-cloud): bump forest-cli to try to fix an issue with mongoose on bootstrap command

---

packages/agent/src/agent.ts
packages/agent/test/agent.test.ts
packages/datasource-customizer/src/datasource-customizer.ts
packages/datasource-customizer/src/decorators/decorators-stack-base.ts
packages/datasource-customizer/src/decorators/decorators-stack-no-code.ts
packages/datasource-customizer/src/decorators/decorators-stack.ts
packages/datasource-customizer/test/collection-customizer.test.ts
packages/datasource-customizer/test/datasource-customizer.test.ts
packages/datasource-customizer/test/datasource-customizer.unit.test.ts
packages/datasource-customizer/test/decorators/decorators-stack-no-code.unit.test.ts
packages/datasource-customizer/test/decorators/decorators-stack.unit.test.ts

feat: allow reload agent

---

packages/agent/package.json
packages/forestadmin-client/package.json
yarn.lock

fix(vulnerability): bump openid-client

---

packages/agent/src/services/serializer.ts
packages/agent/test/services/serializer.test.ts

feat(has-many): allow user to retrieve data when primary key contains special characters

---

packages/datasource-customizer/src/decorators/lazy-join/collection.ts

fix(lazy join): avoid crash when there is no filter to refine

---

packages/datasource-customizer/src/datasource-customizer.ts
packages/datasource-customizer/src/decorators/publication/datasource.ts
packages/datasource-customizer/test/decorators/publication/datasource.test.ts

feat: show a warning in case a mongoose relationship is omitted

---

packages/datasource-customizer/src/datasource-customizer.ts
packages/datasource-customizer/src/decorators/decorators-stack-base.ts

fix(agent): backup and restore stack properly when reload

---

packages/_example/package.json
packages/agent/package.json
packages/forestadmin-client/package.json
yarn.lock

fix(vulnerability): bump superagent -> formidable

---

packages/datasource-mongoose/src/mongoose/schema.ts

fix(mongoose): change regex to support windows os when making introspection

---

lerna.json
package.json
yarn.lock

fix(vulnerability): bump lerna

---

packages/datasource-sql/package.json
yarn.lock

fix(vulnerability): bump socks

---

packages/_example/src/forest/typings.ts
packages/agent/src/utils/condition-tree-parser.ts
packages/agent/test/utils/condition-tree-parser.test.ts

feat(filters): support Not In operator

---

packages/datasource-customizer/src/collection-customizer.ts
packages/datasource-customizer/src/datasource-customizer.ts
packages/datasource-customizer/src/decorators/validation/collection.ts

fix(datasource customizer): fix nullable customization to avoid crash with no code customization

---

packages/agent/src/agent.ts
packages/agent/src/routes/modification/action/action.ts
packages/agent/src/types.ts
packages/agent/src/utils/forest-schema/generator-actions.ts
packages/agent/src/utils/forest-schema/generator-collection.ts
packages/agent/src/utils/forest-schema/generator.ts
packages/agent/test/__factories__/forest-admin-http-driver-options.ts
packages/agent/test/utils/forest-schema/generator-actions.test.ts
packages/agent/test/utils/forest-schema/generator-collection.test.ts
packages/agent/test/utils/forest-schema/generator.test.ts

feat(agent): add unsafe sa endpoint option

---

packages/datasource-mongoose/src/collection.ts
packages/datasource-mongoose/test/integration/many-to-many/_build-models.ts
packages/datasource-mongoose/test/integration/many-to-many/collection_delete.test.ts

fix(datasource mongoose): remove sub array element

---

.github/workflows/notify-ci-failure.yml
.github/workflows/vulnerability-scan.yml

ci(security / build): send slack message for security report and build failure
