ForestAdmin/agent-nodejs

packages/agent/src/builder/collection.ts, packages/agent/test/agent/routes/access/chart.test.ts, packages/agent/test/agent/utils/forest-schema/generator-fields_column.test.ts, packages/agent/test/builder/collection.test.ts, packages/datasource-toolkit/src/decorators/relation/collection.ts, packages/datasource-toolkit/src/interfaces/query/condition-tree/equivalence.ts, packages/datasource-toolkit/test/__factories__/schema/column-schema.ts, packages/datasource-toolkit/test/decorators/relation/collection.test.ts, packages/datasource-toolkit/test/decorators/segment/collection.test.ts, packages/datasource-toolkit/test/utils/collection.test.ts, packages/datasource-toolkit/test/validation/condition-tree.test.ts
`ColumnSchema.filterOperators` is marked as optional in `packages/datasource-toolkit/src/interfaces/schema.ts`
When not provided, the field should just be assumed not to support any operator, however currently this cause the agent to crash.
To replicate the issue, comment out the filterOperator definition in any datasource and start the example project
=> fix: do not crash when operators are not provided by the datasource

.vscode/settings.json, packages/datasource-firebase/LICENSE, packages/datasource-firebase/jest.config.ts, packages/datasource-firebase/package.json, packages/datasource-firebase/test/index.test.ts, packages/datasource-firebase/tsconfig.eslint.json, packages/datasource-firebase/tsconfig.json
=> chore: create firebase package directory

docs/agent-customization/fields/filter.md, docs/agent-customization/relationships/under-the-hood.md, docs/agent-customization/search.md
=> docs: improve documentation by removing some typos

packages/datasource-toolkit/src/interfaces/query/projection/factory.ts, packages/datasource-toolkit/test/interfaces/projection-factory.test.ts
=> feat: add a factory to generate a projection which contains colums of a collection

packages/agent/src/agent/utils/forest-schema/generator-fields.ts, packages/agent/test/agent/utils/forest-schema/generator-fields_many-to-many.test.ts, packages/agent/test/agent/utils/forest-schema/generator-fields_one-to-many.test.ts, packages/agent/test/agent/utils/forest-schema/generator-fields_one-to-one.test.ts
=> fix(schema): mark relations as readonly when the foreign key is readonly

packages/agent/src/builder/agent.ts, packages/datasource-toolkit/src/decorators/rename-collection/collection.ts, packages/datasource-toolkit/src/decorators/rename-collection/datasource.ts, packages/datasource-toolkit/src/decorators/rename-field/collection.ts, packages/datasource-toolkit/src/index.ts, packages/datasource-toolkit/test/decorators/rename-collection/datasource.test.ts, packages/datasource-toolkit/test/decorators/rename-field/collection.test.ts
=> fix: rename collection should also rename in the datasource

packages/_example/src/forest/customizations/rental.ts, packages/datasource-sequelize/src/collection.ts, packages/datasource-sequelize/src/utils/aggregation.ts, packages/datasource-sequelize/src/utils/serializer.ts, packages/datasource-sequelize/test/collection.test.ts
=> fix(datasource-sequelize): serialize record to transform date to iso string 

packages/agent/src/agent/routes/security/authentication.ts, packages/agent/test/agent/routes/security/authentication.test.ts
=> fix(route): remove useless logout route

packages/agent/src/builder/utils/options-validator.ts, packages/agent/test/builder/utils/http-driver-options.test.ts
Close #399
Final decision is the one describe [here](https://developers.google.com/maps/url-encoding) without:
- reserved character 
- `.` that shouldn't be supported in prefix.
`\w` handle `[a-zA-Z0-0_]`, so this should be ok
=> fix(prefix): fix prefix validation regexp

.github/workflows/build.yml
(CI is failling on beta due to a timeout limit that have been reached multiple time in the past merge)
I'm still testing though, as this issue seems to only happen on the beta branch
=> chore(ci): increase test computation timeout

packages/agent/src/agent/routes/index.ts, packages/agent/src/agent/routes/modification/update-field.ts, packages/agent/test/agent/routes/index.test.ts, packages/agent/test/agent/routes/modification/update-field.test.ts
The example project does not have any writable embedded relation...
To have one:
- Edit _example/src/forest/agent.ts
- Replace `bills.items` by `bills` on line 45
- You should have an embedded relation on the "account bills" models
=> fix(mongoose): implement route to submit related data edition

packages/agent/src/services/authorization/internal/action-permission.ts, packages/agent/test/__factories__/authorization/internal/action-permission.ts, packages/agent/test/services/authorization/authorization.test.ts, packages/agent/test/services/authorization/internal/action-permission.test.ts
…(#474)"
This reverts commit 0e0f511730363e2761a1385c01d4ffcec14cfc5e.
=> revert: remove unused canOneOf internal authorisation function

.github/workflows/build.yml
Reverts ForestAdmin/agent-nodejs#493
=> chore: revert "chore(force-release): use the github_token to authenticate the user instead of GH_TOKEN"

packages/agent/src/services/serializer.ts, packages/agent/src/utils/query-string.ts, packages/agent/test/utils/query-string.test.ts, packages/datasource-customizer/src/decorators/collection-decorator.ts, packages/datasource-customizer/src/decorators/computed/collection.ts, packages/datasource-customizer/src/decorators/relation/collection.ts, packages/datasource-customizer/src/decorators/rename-field/collection.ts, packages/datasource-customizer/test/decorators/collection-decorator.test.ts, packages/datasource-toolkit/src/interfaces/query/projection/index.ts, packages/datasource-toolkit/test/interfaces/projection.test.ts
Took one hour to do that with `ab` + `vs code CPU profiler`
The request I'm testing in `ab` is the list of the `account` collection in the `_example` project.
Before:
```
Time taken for tests:   15.564 seconds
Complete requests:      5000
Failed requests:        0
Total transferred:      37740000 bytes
HTML transferred:       36400000 bytes
Requests per second:    321.26 [#/sec] (mean)
Time per request:       31.127 [ms] (mean)
Time per request:       3.113 [ms] (mean, across all concurrent requests)
Transfer rate:          2368.04 [Kbytes/sec] received
```
After:
```
Time taken for tests:   10.487 seconds
Complete requests:      5000
Failed requests:        0
Total transferred:      37515000 bytes
HTML transferred:       36175000 bytes
Requests per second:    476.78 [#/sec] (mean)
Time …
```
=> perf(customizer): improve CPU usage and response time

packages/plugin-aws-s3/src/types.ts, packages/plugin-aws-s3/src/utils/s3.ts
Add S3Client endpoint option, to use AWS S3 plugin with other S3-compatible object storage services.
=> feat(plugin-aws-s3): add S3Client endpoint option

.github/workflows/build.yml
This also reduce by quite a lot the number of files that jest needs to scan + the time it takes to generate the coverage
Before: 
After:
=> chore(ci): improve code coverage output

packages/forestadmin-client/package.json, packages/forestadmin-client/src/permissions/rendering-permission.ts, yarn.lock
=> chore(forestadmin-client): bump lru-cache to latest version

packages/datasource-customizer/src/decorators/write/write-replace/collection.ts, packages/datasource-customizer/src/decorators/write/write-replace/context.ts, packages/datasource-customizer/src/decorators/write/write-replace/types.ts, packages/datasource-customizer/src/index.ts, packages/plugin-aws-s3/src/field/create-field.ts, packages/plugin-aws-s3/src/field/make-field-deleteable.ts, packages/plugin-aws-s3/src/field/make-field-writable.ts, packages/plugin-aws-s3/src/index.ts, packages/plugin-aws-s3/src/types.ts, packages/plugin-aws-s3/test/index.test.ts
This PR has been done to allow customers to differentiate the path in their bucket, and the path stored in the database. 
The new storeAt attribute allows to configure two different logics to compute AWSPath and databasePath. 
Knowing the two paths can now be different, we also need a logic to reconcile the database stored value with the actual path  in the bucket. 
Customers also found really restrictive to be given only the record id in the storeAt conf, I've changed that so it is now asynchronous and provides the context as-well.
=> feat(config): configuration now allows to differenciate bucket path and database path

packages/datasource-mongoose/src/collection.ts, packages/datasource-mongoose/test/integration/flattener/_build-models.ts, packages/datasource-mongoose/test/integration/flattener/collection_create.test.ts
=> fix(datasource-mongoose): when combining asModels and asFields, collection.create returns invalid records for subcollections

packages/datasource-sql/src/introspection/introspector.ts, packages/datasource-sql/test/introspection/intropector.test.ts
=> fix: detect and log broken relationship

packages/datasource-mongoose/src/collection.ts, packages/datasource-mongoose/src/utils/pipeline/lookup.ts, packages/datasource-mongoose/test/integration/flattener/collection_create.test.ts, packages/datasource-mongoose/test/integration/flattener/collection_list.test.ts
=> fix(datasource-mongoose): fix errors when creating or retrieving records from collections created with asModel on an object field

packages/agent/src/agent.ts, packages/forestadmin-client/src/schema/index.ts, packages/forestadmin-client/test/schema/index.test.ts
Copy of https://github.com/ForestAdmin/agent-nodejs/pull/866 so that the CI is not broken due to Fork
=> feat(forestadmin-client): add schema hash to startup logs

packages/agent/src/utils/forest-schema/column-schema-validation.ts, packages/agent/src/utils/forest-schema/generator-fields.ts, packages/agent/test/utils/forest-schema/column-schema-validation.test.ts, packages/agent/test/utils/forest-schema/generator-fields_column.test.ts
=> fix(schema): throw an error when enum values are corrupted in the schema

packages/datasource-customizer/src/typing-generator.ts, packages/datasource-customizer/test/typing-generator.test.ts
Initially I had implemented sorting for enum values but also plain, nested and flat field names; when rebasing on main I realized someone else had done it in the meantine. Thus there are only additional tests for these, but enum values are still now sorted. This prevents the kind of problem I've had on my project when generating the typings file:
=> feat(datasource-customizer): sort enum values in typings file

packages/datasource-customizer/src/decorators/actions/context/single.ts, packages/datasource-customizer/test/decorators/actions/context.test.ts
This is not much, but it helps when declaring single actions which use data from the selected record.
It's a major eyesore in the codebase I'm currently working in, as the field names are quite long, and this pattern is everywhere!
The templating is so that the output of the function have the proper type
Go from this:
```
{
label: 'Street',
isRequired: true,
type: 'String',
defaultValue: async (context) =>
(await context.getRecord(['company:street'])).company?.street,
}
```
to this
```
{
label: 'Street',
isRequired: true,
type: 'String',
defaultValue: (context) => context.getField('company:street')
}
```
=> feat(datasource-customizer): add helper to fetch values from selected record in single actions

packages/datasource-customizer/src/decorators/operators-emulate/collection.ts, packages/datasource-customizer/test/decorators/operators-emulate/collection.test.ts
=> fix(replaceFieldOperator): disallow to pass null because it will emulate instead to remove the operator

packages/cloud-toolkit/src/services/http-forest-server.ts
=> fix(cloud-toolkit): remove a condition in error handler to make the bootstrap work again

packages/forest-cloud/src/commands/logs.ts, packages/forest-cloud/src/commands/version.ts, packages/forest-cloud/test/commands/version.test.ts
=> fix(forest-cloud): display an error when the command does not exist

packages/plugin-flattener/src/flatten-column/customization.ts, packages/plugin-flattener/src/flatten-column/index.ts, packages/plugin-flattener/src/flatten-json-column/index.ts, packages/plugin-flattener/src/index.ts, packages/plugin-flattener/test/flatten-column.test.ts, packages/plugin-flattener/test/flatten-json-column.test.ts, packages/plugin-flattener/test/flatten-json-column.unit.test.ts, packages/plugin-flattener/test/index.test.ts
=> feat(flattener): allow users to flatten JSON primitive column

packages/forest-cloud/src/services/http-server.ts, packages/forest-cloud/test/services/http-server.unit.test.ts
you can test with the following token:
```
eJraWQiOiJvd1ZNUExBckJtcXlSRGh1WGlNaXUwQXFpTW8tVE9EZHRQcUFkU0lxSEw0IiwiYWxnIjoiUlMyNTYifQ.eyJkYXRhIjp7ImRhdGEiOnsidHlwZSI6InVzZXJzIiwiaWQiOiIyODQiLCJhdHRyaWJ1dGVzIjp7ImZpcnN0X25hbWUiOiJEZW1vIiwibGFzdF9uYW1lIjoiVXNlciIsImVtYWlsIjoiaGVsbG9AZm9yZXN0YWRtaW4uY29tIn19fSwiaXNBcHBsaWNhdGlvblRva2VuIjp0cnVlLCJhdWQiOiJGT1JFU1RfVVNFUlMiLCJpc3MiOiJGT1JFU1RfQVVUSEVOVElDQVRJT05fU1lTVEVNIiwiaWF0IjoxNzExNDY3NTQ2LCJleHAiOjQ4NjcyMjc1NDZ9.Vs0nJuPC75u-Mu0VX96-RgK4i2tf8gjTYDC61gtfe3_VQch_R1IieFrVQStaKDyHsZTK8Iy0WbVS7qTdX6aZYyJO_DZurOvYUc2Rcj36oS8WzPYWQFwhIw9fVXxkDGOGbNo5iIw3ZVvgzdiTnEamC0AN7chwAfhJjz--Ulx9CbOXu1UTcdcE2FMbjGVjS1AZh5Il7_YVOpWcMjLu5GXQWBfwsNURY5sDGUIojHRMYlQNkSNb1P7faHjGjApPXfMK9IpnQ1lmmOJXltPgpx2FQbG7KhSmyoX16SP0453Teoaek84eD9aLylwaLrgUk3q746aX37E-Gi_ax6 …
```
=> feat: improve error message in case of invalid token

packages/datasource-customizer/src/types.ts
Hello!
I noticed this small issue while working.
Did not want to bother you guys on the community forums for such a small patch
and besides, it's my name on the git blame (yes, I checked)
=> fix(datasource-customizer): correct confusing type when using addExternalRelation

packages/agent/src/framework-mounter.ts, packages/agent/test/framework-mounter.test.ts
=> fix: when customer passes 0 as port on standalone server it was considered as undefined instead of generating a random available port

packages/agent/src/agent.ts, packages/datasource-customizer/src/collection-customizer.ts, packages/datasource-customizer/src/datasource-customizer.ts, packages/datasource-customizer/src/decorators/decorators-stack-base.ts, packages/datasource-customizer/src/decorators/decorators-stack-no-code.ts, packages/datasource-customizer/src/decorators/decorators-stack.ts, packages/datasource-customizer/test/decorators/decorators-stack-no-code.unit.test.ts
=> fix(customizer-stack): reduce customizer stack to avoid issues

packages/datasource-sequelize/src/utils/query-converter.ts, packages/datasource-sequelize/test/integration/list/filter.integration.test.ts
linked to: CU-86bzhg9kj
…en, it should return all the records
=> fix(datasource-sequelize): returns all records when NotIn is given with empty array

packages/datasource-sql/src/orm-builder/model.ts, packages/datasource-sql/test/orm-builder/model.test.ts
=> fix(datasource-sql): support for paranoid tables with snake case timestamp fields

packages/datasource-sequelize/src/utils/model-to-collection-schema-converter.ts, packages/datasource-sequelize/test/utils/model-to-collection-schema-converter.test.ts, packages/datasource-sql/test/_helpers/connection-details.ts
=> fix(sequelize): model validation should handle correctly is validator

packages/datasource-mongoose/src/utils/pipeline/filter.ts, packages/datasource-mongoose/test/integration/review/collection_list.test.ts
=> fix(mongoose): apply sort on all pages instead of the current page

packages/datasource-toolkit/src/interfaces/action.ts
=> fix: missing exported type

packages/agent/src/routes/system/error-handling.ts, packages/agent/src/routes/system/logger.ts, packages/agent/src/types.ts, packages/agent/test/routes/index.test.ts, packages/agent/test/routes/system/error-handling.test.ts, packages/agent/test/routes/system/logger.test.ts
=> fix(logger): logger should display the right status code in case of error

packages/agent/src/routes/capabilities.ts, packages/agent/src/routes/index.ts, packages/agent/src/utils/forest-schema/filterable.ts, packages/agent/src/utils/forest-schema/generator-fields.ts, packages/agent/test/routes/capabilities.test.ts, packages/agent/test/routes/index.test.ts, packages/agent/test/utils/forest-schema/filterable.test.ts
=> feat(capabilities): register capabilities route for field filter operators

packages/datasource-customizer/src/decorators/relation/collection.ts
=> fix: ignore inconsistent foreign key types

packages/forest-cloud/src/commands/bootstrap.ts, packages/forest-cloud/src/services/bootstrap.ts, packages/forest-cloud/test/commands/bootstrap.test.ts, packages/forest-cloud/test/services/bootstrap.unit.test.ts
=> fix(forest-cloud): generate datasource file on bootstrap

packages/agent/src/routes/access/get.ts, packages/agent/src/utils/query-string.ts, packages/agent/test/routes/access/get.test.ts
=> feat: add support of projection on get route

packages/forestadmin-client/src/utils/server.ts, packages/forestadmin-client/test/utils/server.test.ts
=> feat: better logs during timeout

package.json, yarn.lock
=> fix(security): patch tar dependency vulnerabilities

packages/agent/src/routes/capabilities.ts, packages/agent/test/routes/capabilities.test.ts, packages/datasource-customizer/src/decorators/composite-datasource.ts, packages/datasource-customizer/test/decorators/composite-datasource.test.ts, packages/datasource-customizer/test/decorators/decorators-stack-no-code.unit.test.ts, packages/datasource-customizer/test/decorators/decorators-stack.unit.test.ts, packages/datasource-mongo/.gitignore, packages/datasource-mongo/docker-compose.yml, packages/datasource-sequelize/src/datasource.ts, packages/datasource-sequelize/src/index.ts, packages/datasource-sequelize/src/types.ts, packages/datasource-sequelize/test/datasource.unit.test.ts, packages/datasource-sql/docker-compose.yml, packages/datasource-sql/src/index.ts, packages/datasource-sql/src/types.ts, packages/datasource-sql/test/index.test.ts, packages/datasource-toolkit/src/base-datasource.ts, packages/datasource-toolkit/src/decorators/datasource-decorator.ts, packages/datasource-toolkit/src/interfaces/collection.ts, packages/datasource-toolkit/test/__factories__/datasource.ts, packages/datasource-toolkit/test/base-datasource.test.ts, packages/datasource-toolkit/test/decorators/datasource-decorator.test.ts
=> chore(capabilities): define native query connection capabilities

packages/datasource-customizer/src/decorators/rename-field/collection.ts, packages/datasource-customizer/test/decorators/rename-field/collection.test.ts
=> fix(rename decorator): properly map relation when renaming pk field

packages/datasource-toolkit/src/interfaces/query/condition-tree/equivalence.ts, packages/datasource-toolkit/src/interfaces/query/condition-tree/transforms/time.ts, packages/datasource-toolkit/test/interfaces/transforms/dateonly.test.ts
=> fix: filtering on dateOnly fields now interprets interval properly

.github/workflows/build.yml
=> ci: use v4 actions

packages/forestadmin-client/src/utils/ttl-cache.ts, packages/forestadmin-client/test/utils/ttl-cache.test.ts
**Current issue:**
Sometimes our app would be stuck due to the following error in our logs: `"Error: The request to Forest Admin server has timed out while trying to reach https://api.forestadmin.com/liana/v4/permissions/environment"`.
This would make our app unusable (since it can't reach Forest) and we had to restart the pod to make it work again.
**Root cause:**
The code responsible for calling the "https://api.forestadmin.com/liana/v4/permissions/environment" URL, in [ActionPermissionService](https://github.com/ForestAdmin/agent-nodejs/blob/main/packages/forestadmin-client/src/permissions/action-permission.ts#L87), uses a [TTLCache](https://github.com/ForestAdmin/agent-nodejs/blob/main/packages/forestadmin-client/src/utils/ttl-cache.ts), which keeps returning the **same** timed out …
=> fix: don't cache rejected promises

packages/datasource-mongo/package.json, packages/datasource-mongo/src/connection/create-connection.ts, packages/datasource-mongo/test/connection/create-connection.unit.test.ts, yarn.lock
I upgrade ssh-tunnel dependency because the maintainer merges our contribution to fix this issue: https://github.com/agebrock/tunnel-ssh/pull/121
=> fix: upgrade ssh-tunnel dependency to avoid crash when "no response from server"

packages/agent/src/routes/access/count.ts, packages/agent/src/routes/access/list.ts, packages/agent/src/services/index.ts, packages/agent/src/services/segment-query-handler.ts, packages/agent/test/__factories__/forest-admin-http-driver-services.ts, packages/agent/test/__factories__/segment-query-handler.ts, packages/agent/test/services/segment-query-handler.test.ts, packages/datasource-customizer/src/decorators/segment/collection.ts, packages/datasource-customizer/test/decorators/segment/collection.test.ts, packages/datasource-toolkit/src/interfaces/query/filter/unpaginated.ts
=> feat(segment): support templating for segment live query

packages/datasource-customizer/src/collection-customizer.ts, packages/datasource-customizer/src/decorators/search/collection.ts, packages/datasource-customizer/test/collection-customizer.test.ts, packages/datasource-customizer/test/decorators/search/collections.test.ts
=> feat: allow disable search on collection

packages/_example/src/forest/agent.ts, packages/datasource-customizer/src/decorators/decorators-stack.ts, packages/datasource-customizer/src/decorators/lazy-join/collection.ts, packages/datasource-customizer/test/decorators/lazy-join/collection.test.ts
=> feat: add lazy join decorator

packages/forestadmin-client/src/permissions/user-permission.ts, packages/forestadmin-client/test/permissions/user-permission.test.ts
(Follows the same issue on action-permission: https://github.com/ForestAdmin/agent-nodejs/pull/1238)
Sometimes our app would be stuck due to the following error in our logs: "Error: The request to Forest Admin server has timed out while trying to reach https://api.forestadmin.com/liana/v4/permissions/users".
This would make our app unusable (since it can't reach Forest) and we had to restart the pod to make it work again.
The code responsible for calling the "https://api.forestadmin.com/liana/v4/permissions/users" URL, in [UserPermissionService](https://github.com/ForestAdmin/agent-nodejs/blob/main/packages/forestadmin-client/src/permissions/user-permission.ts), uses a cache which keeps returning the same timed out promise.
Don't cache rejected promises, so that the following calls will …
=> fix(user-permission): don't cache rejected promises

packages/datasource-mongoose/src/datasource.ts, packages/datasource-mongoose/src/types.ts, packages/datasource-mongoose/test/datasource.test.ts, packages/datasource-mongoose/test/integration/review/collection_list.test.ts
=> feat(mongoose): allow to enable debug mode

.github/workflows/build.yml, packages/datasource-mongoose/test/datasource.test.ts, packages/forestadmin-client/src/events-subscription/index.ts, packages/forestadmin-client/test/events-subscription/index.test.ts
=> fix(sse): detect buffering and warn user

packages/plugin-aws-s3/src/types.ts, packages/plugin-aws-s3/src/utils/s3.ts
In plugin-aws-s3 for people using S3 based solution (but not AWS) like Localstack in a local environment we should allow the forcePathStyle option in order to support these solution.
Work perfectly without for getting PreSignedUrl but not with the PutObjectCommand
=> feat(plugin-aws-s3): add force path style parameter to s3 client

packages/datasource-mongoose/src/mongoose/schema.ts, packages/datasource-mongoose/src/utils/schema/fields.ts, packages/datasource-mongoose/src/utils/schema/is-schema-type.ts, packages/datasource-mongoose/src/utils/version-manager.ts
=> fix: prevent stack overflow error during mongoose introspection

packages/datasource-customizer/src/collection-customizer.ts, packages/datasource-customizer/src/datasource-customizer.ts, packages/datasource-customizer/test/collection-customizer.test.ts
=> feat(customizer): customers can now mark a field as optional
